### ISSUE TITLE
Not shown in broswer

### ISSUE THREAD

**Issue by HaViGit** [sdetweil/MagicMirror_scripts#10]
First off all thanks for your work and script! Just used it to install MM on my RPi 3B+ and the script seems to work as expected. Everything looks okay after "pm2 start MagicMirror", please see the image:

https://echtsing.nl/MM.JPG

But, when trying to see MM in my browser via http://192.168.2.185:8080/ it reports connection problems with the server (not reachable) and MM is not shown. No matter if I use Chrome or Firefox, both on Windows 10. The RPi is reachable via SSH in a terminal without any issues. A previous installation of MM in the same home network worked for months.

Do you have any idea what I am doing wrong? Can you advice me how to solve this?

**Comment by sdetweil** [comment]
the default MM config only allows apps ON the mirror system to connect
change the mm/config/config.js

address:"0.0.0.0",
ipWhitelist:[],
this allows any app anywhere on your network to connect to the mirror
you can add ipwhitelist entries to filter to just specific systems.. etc..

**Comment by sdetweil** [comment]
ton of stuff to know all at once... ! 
info from doc, not as clear, but 
https://docs.magicmirror.builders/getting-started/configuration.html#general
