### ISSUE TITLE
Feature Request: Install emoji fonts during install

### ISSUE THREAD

**Issue by mickecamino** [sdetweil/MagicMirror_scripts#103]
Not a serious issue, but I (as many others) use emojis in the calendar. This requires that the Noto Color Emoji font is installed.
Could this be included in the script? My MM crashed due to a faulty SD-card. I had a backup of the MM folder. I used this script to install MM on a new SD card, installed all my modules and restored the config file. 
Only thing that was missing was the emoji font.

**Comment by sdetweil** [comment]
does this create a folder in the css folder? 

I think this would be better in the backup/restore scripts.

**Comment by mickecamino** [comment]
No, it is added via apt:
`sudo apt install fonts-noto-color-emoji`

**Comment by sdetweil** [comment]
I really dont want to get into installing system extensions that don't contribute to MM install.  then there will be a list that I have to discover and maintain.

**Comment by mickecamino** [comment]
OK, I just add it to my TODO-list when installing MM. Closing the ticket.
