### ISSUE TITLE
I failed.

### ISSUE THREAD

**Issue by uok825** [sdetweil/MagicMirror_scripts#11]
First Log:
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'eslint' ]
2 info using npm@6.14.4
3 info using node@v10.21.0
4 verbose npm-session ba5cf929b9647f74
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for eslint@latest Cannot read property 'resolve' of undefined
8 timing stage:rollbackFailedOptional Completed in 29ms
9 timing stage:runTopLevelLifecycles Completed in 1206ms
10 verbose stack TypeError: Cannot read property 'resolve' of undefined
10 verbose stack     at regFetch (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js:88:23)
10 verbose stack     at fetchPackument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/packument.js:42:10)
10 verbose stack     at packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/packument.js:20:10)
10 verbose stack     at getManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:22:10)
10 verbose stack     at manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:13:10)
10 verbose stack     at Object.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/index.js:17:12)
10 verbose stack     at Object.Fetcher#manifest [as manifest] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/protoduck/node_modules/genfun/lib/genfun.js:15:38)
10 verbose stack     at manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetch.js:23:18)
10 verbose stack     at pinflight (/usr/local/lib/node_modules/npm/node_modules/pacote/manifest.js:24:12)
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:29:24
10 verbose stack     at Promise._execute (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/debuggability.js:313:9)
10 verbose stack     at Promise._resolveFromExecutor (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:488:18)
10 verbose stack     at new Promise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:79:10)
10 verbose stack     at _inflight (/usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:28:25)
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:22:14
10 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose cwd /home/pi/MagicMirror
12 verbose Linux 4.19.118+
13 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "eslint"
14 verbose node v10.21.0
15 verbose npm  v6.14.4
16 error Cannot read property 'resolve' of undefined
17 verbose exit [ 1, true ]
`
Second Log:
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--only=prod' ]
2 info using npm@6.14.4
3 info using node@v10.21.0
4 verbose npm-session 228e2a4f5ca6799e
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall magicmirror@2.11.0
7 info lifecycle magicmirror@2.11.0~preinstall: magicmirror@2.11.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 442ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 8ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 175ms
16 silly install loadAllDepsIntoIdealTree
17 silly fetchPackageMetaData error for chai@^4.1.2 Cannot read property 'resolve' of undefined
18 silly fetchPackageMetaData error for chai-as-promised@^7.1.1 Cannot read property 'resolve' of undefined
19 silly fetchPackageMetaData error for current-week-number@^1.0.7 Cannot read property 'resolve' of undefined
20 silly fetchPackageMetaData error for danger@^3.1.3 Cannot read property 'resolve' of undefined
21 silly fetchPackageMetaData error for grunt@latest Cannot read property 'resolve' of undefined
22 silly fetchPackageMetaData error for grunt-eslint@latest Cannot read property 'resolve' of undefined
23 silly fetchPackageMetaData error for grunt-jsonlint@latest Cannot read property 'resolve' of undefined
24 silly fetchPackageMetaData error for grunt-markdownlint@latest Cannot read property 'resolve' of undefined
25 silly fetchPackageMetaData error for grunt-stylelint@latest Cannot read property 'resolve' of undefined
26 silly fetchPackageMetaData error for grunt-yamllint@latest Cannot read property 'resolve' of undefined
27 silly fetchPackageMetaData error for http-auth@^3.2.3 Cannot read property 'resolve' of undefined
28 silly fetchPackageMetaData error for jsdom@^11.6.2 Cannot read property 'resolve' of undefined
29 silly fetchPackageMetaData error for mocha@^7.0.0 Cannot read property 'resolve' of undefined
30 silly fetchPackageMetaData error for mocha-each@^1.1.0 Cannot read property 'resolve' of undefined
31 silly fetchPackageMetaData error for mocha-logger@^1.0.6 Cannot read property 'resolve' of undefined
32 silly fetchPackageMetaData error for spectron@^8.0.0 Cannot read property 'resolve' of undefined
33 silly fetchPackageMetaData error for stylelint@latest Cannot read property 'resolve' of undefined
34 silly fetchPackageMetaData error for stylelint-config-standard@latest Cannot read property 'resolve' of undefined
35 silly fetchPackageMetaData error for time-grunt@latest Cannot read property 'resolve' of undefined
36 silly fetchPackageMetaData error for colors@^1.1.2 Cannot read property 'resolve' of undefined
37 silly fetchPackageMetaData error for console-stamp@^0.2.9 Cannot read property 'resolve' of undefined
38 silly fetchPackageMetaData error for express@^4.16.2 Cannot read property 'resolve' of undefined
39 silly fetchPackageMetaData error for express-ipfilter@^1.0.1 Cannot read property 'resolve' of undefined
40 silly fetchPackageMetaData error for feedme@latest Cannot read property 'resolve' of undefined
41 silly fetchPackageMetaData error for helmet@^3.21.2 Cannot read property 'resolve' of undefined
42 silly fetchPackageMetaData error for iconv-lite@latest Cannot read property 'resolve' of undefined
43 silly fetchPackageMetaData error for lodash@^4.17.15 Cannot read property 'resolve' of undefined
44 silly fetchPackageMetaData error for module-alias@^2.2.2 Cannot read property 'resolve' of undefined
45 silly fetchPackageMetaData error for moment@latest Cannot read property 'resolve' of undefined
46 silly fetchPackageMetaData error for request@^2.88.0 Cannot read property 'resolve' of undefined
47 silly fetchPackageMetaData error for rrule@^2.6.2 Cannot read property 'resolve' of undefined
48 silly fetchPackageMetaData error for rrule-alt@^2.2.8 Cannot read property 'resolve' of undefined
49 silly fetchPackageMetaData error for simple-git@^1.85.0 Cannot read property 'resolve' of undefined
50 silly fetchPackageMetaData error for socket.io@^2.1.1 Cannot read property 'resolve' of undefined
51 silly fetchPackageMetaData error for valid-url@latest Cannot read property 'resolve' of undefined
52 silly fetchPackageMetaData error for electron@^6.1.7 Cannot read property 'resolve' of undefined
53 silly fetchPackageMetaData error for colors@^1.1.2 Cannot read property 'resolve' of undefined
54 silly fetchPackageMetaData error for console-stamp@^0.2.9 Cannot read property 'resolve' of undefined
55 silly fetchPackageMetaData error for express@^4.16.2 Cannot read property 'resolve' of undefined
56 silly fetchPackageMetaData error for express-ipfilter@^1.0.1 Cannot read property 'resolve' of undefined
57 silly fetchPackageMetaData error for feedme@latest Cannot read property 'resolve' of undefined
58 silly fetchPackageMetaData error for helmet@^3.21.2 Cannot read property 'resolve' of undefined
59 silly fetchPackageMetaData error for iconv-lite@latest Cannot read property 'resolve' of undefined
60 silly fetchPackageMetaData error for lodash@^4.17.15 Cannot read property 'resolve' of undefined
61 silly fetchPackageMetaData error for module-alias@^2.2.2 Cannot read property 'resolve' of undefined
62 silly fetchPackageMetaData error for moment@latest Cannot read property 'resolve' of undefined
63 silly fetchPackageMetaData error for request@^2.88.0 Cannot read property 'resolve' of undefined
64 silly fetchPackageMetaData error for rrule@^2.6.2 Cannot read property 'resolve' of undefined
65 silly fetchPackageMetaData error for rrule-alt@^2.2.8 Cannot read property 'resolve' of undefined
66 silly fetchPackageMetaData error for simple-git@^1.85.0 Cannot read property 'resolve' of undefined
67 silly fetchPackageMetaData error for socket.io@^2.1.1 Cannot read property 'resolve' of undefined
68 silly fetchPackageMetaData error for valid-url@latest Cannot read property 'resolve' of undefined
69 silly fetchPackageMetaData error for electron@^6.1.7 Cannot read property 'resolve' of undefined
70 timing stage:rollbackFailedOptional Completed in 15ms
71 timing stage:runTopLevelLifecycles Completed in 3723ms
72 silly saveTree magicmirror@2.11.0
73 warn optional SKIPPING OPTIONAL DEPENDENCY: electron@^6.1.7 (node_modules/electron):
74 warn optional SKIPPING OPTIONAL DEPENDENCY: Cannot read property 'resolve' of undefined
75 verbose stack TypeError: Cannot read property 'resolve' of undefined
75 verbose stack     at regFetch (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js:88:23)
75 verbose stack     at fetchPackument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/packument.js:42:10)
75 verbose stack     at packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/packument.js:20:10)
75 verbose stack     at getManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:22:10)
75 verbose stack     at manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:13:10)
75 verbose stack     at Object.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/index.js:17:12)
75 verbose stack     at Object.Fetcher#manifest [as manifest] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/protoduck/node_modules/genfun/lib/genfun.js:15:38)
75 verbose stack     at manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetch.js:23:18)
75 verbose stack     at pinflight (/usr/local/lib/node_modules/npm/node_modules/pacote/manifest.js:24:12)
75 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:29:24
75 verbose stack     at Promise._execute (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/debuggability.js:313:9)
75 verbose stack     at Promise._resolveFromExecutor (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:488:18)
75 verbose stack     at new Promise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:79:10)
75 verbose stack     at _inflight (/usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:28:25)
75 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:22:14
75 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
76 verbose cwd /home/pi/MagicMirror
77 verbose Linux 4.19.118+
78 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--only=prod"
79 verbose node v10.21.0
80 verbose npm  v6.14.4
81 error Cannot read property 'resolve' of undefined
82 verbose exit [ 1, true ]
`

**Comment by sdetweil** [comment]
the log is ~/install.log

did u install node or npm BEFORE running the script?  the problems appear to be node or npm version related

please reflash the sd card and try again with my script from the start, it does everything

please post the  install.log
thanks

**Comment by sdetweil** [comment]
i'm gonna assume u got this , as u haven't responded.. reopen if still a problem
