### ISSUE TITLE
Suggestion: allow the renaming of the MagicMirror instance in PM2

### ISSUE THREAD

**Issue by BKeyport** [sdetweil/MagicMirror_scripts#12]
Sam, 

I'd like the option on install of MagicMirror to name the PM2 instance something other than "MagicMirror" - I redid mine to "mm", but would be nice to have a prompt that defaults to "MagicMirror" to use a name other than that. 

Thanks!

**Comment by sdetweil** [comment]
i'm open to a pr on that

**Comment by sdetweil** [comment]
@CatoAntonsen you can also use the number of the entry instead of the name

pm2 restart 0

or if no other impacts 'all'

pm2 restart all

**Comment by sdetweil** [comment]
accepted, thanks
