### ISSUE TITLE
Auto boot when quit

### ISSUE THREAD

**Issue by nickreif** [sdetweil/MagicMirror_scripts#13]
When I quit the program to add a module the interface automatically boots up again disabling me from adding modules or doing anything with the pi

**Comment by sdetweil** [comment]
you just minimize the MM ui, alt-spacebar, n, and in a terminal window do pm2 stop 0
then u can test, with pm2 start 0, pm2 stop 0, or pme restart 0 (which will stop/start)

as a 'mirror' is intended to sit on a wall, unattended, one would like it to reboot to the mirror app after a power failure..
that is pm2's job

pm2 --help for more commands and info

**Comment by sdetweil** [comment]
sorry was away for knee surgery and didn't see your issue

**Comment by sdetweil** [comment]
@nickreif  is this problem still causing trouble for you?

**Comment by sdetweil** [comment]
closed,  no response
