### ISSUE TITLE
Upgrade Script Doing Test Only

### ISSUE THREAD

**Issue by cweinhofer** [sdetweil/MagicMirror_scripts#18]
I am trying to use `upgrade-script.sh` to upgrade my MM, but it seems like it only does the test run. The README mentions two ways to run it -- the test run and the actual run -- but the command listed for both seems to be identical. Am I missing something?

**Comment by sdetweil** [comment]
yeh, sorry, got too carried away 'enhancing' the commands to copy.. I just added the word 'apply' at the end

**Comment by cweinhofer** [comment]
Works great now. Thanks for all your hard work on these.
