### ISSUE TITLE
Question to how to start it.

### ISSUE THREAD

**Issue by Playchildren** [sdetweil/MagicMirror_scripts#20]
Thx for the shared coded. Though the issue seems stupid, i really want to know how to start MagicMirror on my pi3.
When i click 'index.html", is empty. So how can i use it through browsers.
Hoping for your reply.

**Comment by sdetweil** [comment]
you do
```
npm start
```

**Comment by sdetweil** [comment]
if you used my install script, then the next to the last line tells u how to start MagicMirror
(you replied NO  to using pm2 to start mm at boot) 

We're ready! Run DISPLAY=:0 npm start from the ~/MagicMirror directory to start your MagicMirror.

(you replied Yes to using pm2 to start MM at boot )

We're ready! Run pm2 start MagicMirror from the ~/MagicMirror directory to start your MagicMirror.

these lines are shown in the ~/install.log file at the end

**Comment by Playchildren** [comment]
Got it. Your advice is very helpful.
Thanks for your reply.
