### ISSUE TITLE
Suggestion: adding custom.css to pm2_MagicMirror.json

### ISSUE THREAD

**Issue by TJuTZu** [sdetweil/MagicMirror_scripts#21]
I am currently manually changing pm2_MagicMirror.json practically every time when I install MagicMirror to be able to easily modify and test changes in custom.css

`"watch":["/home/pi/MagicMirror/config/config.js"], `

to

```
"watch":[
                "/home/pi/MagicMirror/config/config.js",
                "/home/pi/MagicMirror/css/custom.css"
            ],
```

**Comment by sdetweil** [comment]
ok, to test changes, all u have to do is press ctrl-r to refresh the ui, don't have to restart mm

**Comment by TJuTZu** [comment]
I am always using MM trough ssh. I usually never have keyboard attached directly  to device running MM.

**Comment by sdetweil** [comment]
if u set the address:"0.0.0.0", and
ipWhitelist:[], 

you can use chrome or firefox , edge, on your PC to connect to the MM server and  do the same without restarting MM

I use WInscp or bitvise SSH clients, which give you a file manager window over the pi files, double click to open w your favorite editor

**Comment by TJuTZu** [comment]
I never thought that. I have been so used to do everything trough cli that I have totally forgot it.
I am currently using MobaXterm which also have ton of functionalities built in SSH client.

Thanks for the tip.
