### ISSUE TITLE
Suggestion to extend the script to only update modules

### ISSUE THREAD

**Issue by spitzlbergerj** [sdetweil/MagicMirror_scripts#22]
Hi,
I always use your script for the updates. Always works great. Thanks a lot!
The script also updates the modules, but only if MagicMirror has been updated.
Is there a possibility to use the script only to update all modules, even if no MagicMirror update is pending?
That would be a great extension.

**Comment by sdetweil** [comment]
the script does NOT ever update any modules, it only refreshes the module dependencies when MM has changed. 

@Bugsounet has created an automated module updater

**Comment by spitzlbergerj** [comment]
Thanks a lot, I'll try this
