### ISSUE TITLE
WiFi goes down once Magic Mirror is installed

### ISSUE THREAD

**Issue by fsne04** [sdetweil/MagicMirror_scripts#23]
Hi,
I have installed Magic Mirror twice using your script. Each time the Pi4 worked fine until the Magic Mirror Software was installed. Then Wifi went down on the Pi4 (nowhere else) and although the WiFi icon still shows connected to my network, the hovering mouse shows the error: "eth0: Link is down, wlan0: Not associated".  I most definately a noobie and could have done something wrong, but I don't think so, since it is pretty straight forward with the script copying and running it in terminal.
Also, when I don't install Magic Mirror, as well when I use a configured Retropie sd card, the Wifi doesn't go down on the PI4.
Any help, or suggestion would be greatly appreciated.  Best regards, Frank Schroder

**Comment by sdetweil** [comment]
Hm. Only thing the script does is apt-get update and apt-get upgrade. We assume networking works.. no adjustments on any
anything about the
