### ISSUE TITLE
Different behavior during boot with Raspi 3+ and Raspi 4

### ISSUE THREAD

**Issue by Dimasua** [sdetweil/MagicMirror_scripts#24]
When Raspi3+ is booting it is displaying MagicMirror2 logo and just a few system messages are displayed in a single line below the logo. With Raspi4 it is different. It does not display the MagicMirror2 logo and all system messages are visible until the desktop is loaded, like during normal Raspi boot without MagicMirror. 
For both devices I used the same MagicMirror installation script. What can be the reason for that?

**Comment by sdetweil** [comment]
I suspect that the boot screen process changed on latest buster.. will review

**Comment by sdetweil** [comment]
this process works... on pi4 and buster
https://shop.sb-components.co.uk/blogs/posts/customising-splash-screen-on-your-raspberry-pi

**Comment by sdetweil** [comment]
and the prior process (in script) works ok on new release, bullseye
