### ISSUE TITLE
News doesn't load until restart

### ISSUE THREAD

**Issue by noahvb** [sdetweil/MagicMirror_scripts#27]
Default News module will not load when Raspberry Pi Zero boots up. Instance must be restarted (pm2 restart <id>), for the module to load.

**Comment by sdetweil** [comment]
that's not a script problem. 

can u show the pm2 logs after.boit when it doesn't work??

pm2 stop 0
pm2 flush
pm2 start
reboot
minimize mm ( alt-spacebar, n)
ctrl-alt-t to open terminal
pm2 logs --lines=300 >somefile.txt
attach somefile.txt here

**Comment by sdetweil** [comment]
closing, no response
