### ISSUE TITLE
SUGGESTION: Headless WiFi MM installation with Comitup

### ISSUE THREAD

**Issue by Dimasua** [sdetweil/MagicMirror_scripts#28]
Hi Sam,

would it be possible to add [Comitup](https://davesteele.github.io/comitup/) into the MM installation package, so a headless establishing of Wifi networking is possible?

Thanks in advance!

**Comment by sdetweil** [comment]
if it's headless, how are u running my script and replying to the prompts?

**Comment by Dimasua** [comment]
Yes, you are right :) I forgot that I used your scripts over already installed Raspbian OS. What I want to achieve is having a pre-built image on a sd-card so once Raspi is plugged in, it starts the installation automatically and there is no need for SSH or keyboard/mouse connected to Raspi to setup WiFi. So to have a kind of plug'n'play installation.

**Comment by sdetweil** [comment]
currently my script does not support automated mm install.

sam

**Comment by sdetweil** [comment]
wifi setup is now supported by the raspi image downloader
