### ISSUE TITLE
with raspberry pi Zero it fails on ELIFECYCLE error 134

### ISSUE THREAD

**Issue by Smiley-94** [sdetweil/MagicMirror_scripts#3]
here is a complete log:
`
Installing dependencies ...
npm WARN deprecated time-grunt@2.0.0: Deprecated because Grunt is practically unmaintained. Move on to something better. This package will continue to work with Grunt v1, but it will not receive any updates.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated rrule-alt@2.2.8: Please use rrule instead
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated webdriverio@4.14.4: outdated version, please use @next
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
Aborted
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN ws@7.2.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! console-stamp@0.2.9 postinstall: `node ./msg.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the console-stamp@0.2.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-04-11T12_14_24_984Z-debug.log
Unable to install dependencies! 
`

what can I do to fix this?

**Comment by sdetweil** [comment]
can u please post the entire ~/install.log file

i test on pi 0..  what OS level are you using, jessie, stretch, buster??  
needs to be stretch or buster.. jessie is too old

**Comment by Smiley-94** [comment]
I used 2020-02-13-raspbian-buster-full

here is the entire install.log:

> install starting  - sab apr 11 14:01:54 CEST 2020
installing on armv6l processor system
the os is Distributor ID: Raspbian Description: Raspbian GNU/Linux 10 (buster) Release: 10 Codename: buster
[96mUpdating packages ...[90m
Scaricamento di:1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15,0 kB] Scaricamento di:2 http://archive.raspberrypi.org/debian buster InRelease [25,1 kB] Scaricamento di:3 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13,0 MB] Scaricamento di:4 http://archive.raspberrypi.org/debian buster/main armhf Packages [326 kB] Recuperati 13,4 MB in 34s (390 kB/s) Lettura elenco dei pacchetti...
apt-get update  completed ok
apt-get upgrade  started
apt upgrade result =rc=0 Lettura elenco dei pacchetti...
Generazione albero delle dipendenze...
Lettura informazioni sullo stato...
Calcolo dell'aggiornamento...
I seguenti pacchetti saranno aggiornati:
  fonts-opensymbol libreoffice libreoffice-avmedia-backend-gstreamer
  libreoffice-base libreoffice-base-core libreoffice-base-drivers
  libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw
  libreoffice-gtk3 libreoffice-help-common libreoffice-help-en-gb
  libreoffice-help-it libreoffice-impress libreoffice-java-common
  libreoffice-l10n-en-gb libreoffice-l10n-it libreoffice-librelogo
  libreoffice-math libreoffice-nlpsolver libreoffice-report-builder
  libreoffice-report-builder-bin libreoffice-script-provider-bsh
  libreoffice-script-provider-js libreoffice-script-provider-python
  libreoffice-sdbc-firebird libreoffice-sdbc-hsqldb
  libreoffice-sdbc-postgresql libreoffice-style-colibre
  libreoffice-style-tango libreoffice-wiki-publisher libreoffice-writer
  python3-uno uno-libs3 ure
36 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.
È necessario scaricare 97,4 MB di archivi.
Dopo quest'operazione, verranno occupati 0 B di spazio su disco.
Scaricamento di:1 http://archive.raspberrypi.org/debian buster/main armhf fonts-opensymbol all 2:102.10+LibO6.1.5-3+rpi1+deb10u5+rpt1 [273 kB]
Scaricamento di:2 http://archive.raspberrypi.org/debian buster/main armhf ure armhf 6.1.5-3+rpi1+deb10u5+rpt1 [1.580 kB]
Scaricamento di:3 http://archive.raspberrypi.org/debian buster/main armhf uno-libs3 armhf 6.1.5-3+rpi1+deb10u5+rpt1 [747 kB]
Scaricamento di:4 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-base-drivers armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [394 kB]
Scaricamento di:5 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-base armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [1.437 kB]
Scaricamento di:6 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-calc armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [5.654 kB]
Scaricamento di:7 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-impress armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [791 kB]
Scaricamento di:8 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-draw armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [2.011 kB]
Scaricamento di:9 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-gtk3 armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [222 kB]
Scaricamento di:10 http://archive.raspberrypi.org/debian buster/main armhf python3-uno armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [176 kB]
Scaricamento di:11 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-sdbc-postgresql armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [172 kB]
Scaricamento di:12 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-sdbc-hsqldb armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [91,1 kB]
Scaricamento di:13 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-sdbc-firebird armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [98,7 kB]
Scaricamento di:14 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-report-builder-bin armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [644 kB]
Scaricamento di:15 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-math armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [313 kB]
Scaricamento di:16 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-help-it all 1:6.1.5-3+rpi1+deb10u5+rpt1 [1.553 kB]
Scaricamento di:17 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-help-en-gb all 1:6.1.5-3+rpi1+deb10u5+rpt1 [1.489 kB]
Scaricamento di:18 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-help-common all 1:6.1.5-3+rpi1+deb10u5+rpt1 [2.641 kB]
Scaricamento di:19 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-style-tango all 1:6.1.5-3+rpi1+deb10u5+rpt1 [1.200 kB]
Scaricamento di:20 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-style-colibre all 1:6.1.5-3+rpi1+deb10u5+rpt1 [966 kB]
Scaricamento di:21 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-script-provider-python all 1:6.1.5-3+rpi1+deb10u5+rpt1 [13,0 kB]
Scaricamento di:22 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-script-provider-js all 1:6.1.5-3+rpi1+deb10u5+rpt1 [645 kB]
Scaricamento di:23 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-script-provider-bsh all 1:6.1.5-3+rpi1+deb10u5+rpt1 [31,1 kB]
Scaricamento di:24 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-report-builder all 1:6.1.5-3+rpi1+deb10u5+rpt1 [275 kB]
Scaricamento di:25 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-l10n-it all 1:6.1.5-3+rpi1+deb10u5+rpt1 [593 kB]
Scaricamento di:26 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-l10n-en-gb all 1:6.1.5-3+rpi1+deb10u5+rpt1 [525 kB]
Scaricamento di:27 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-java-common all 1:6.1.5-3+rpi1+deb10u5+rpt1 [1.871 kB]
Scaricamento di:28 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-common all 1:6.1.5-3+rpi1+deb10u5+rpt1 [36,1 MB]
Scaricamento di:29 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-base-core armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [594 kB]
Scaricamento di:30 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-avmedia-backend-gstreamer armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [19,5 kB]
Scaricamento di:31 http://archive.raspberrypi.org/debian buster/main armhf libreoffice armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [78,3 kB]
Scaricamento di:32 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-writer armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [6.730 kB]
Scaricamento di:33 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-core armhf 1:6.1.5-3+rpi1+deb10u5+rpt1 [25,1 MB]
Scaricamento di:34 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-librelogo all 1:6.1.5-3+rpi1+deb10u5+rpt1 [234 kB]
Scaricamento di:35 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-nlpsolver all 0.9+LibO6.1.5-3+rpi1+deb10u5+rpt1 [724 kB]
Scaricamento di:36 http://archive.raspberrypi.org/debian buster/main armhf libreoffice-wiki-publisher all 1.2.0+LibO6.1.5-3+rpi1+deb10u5+rpt1 [1.450 kB]
apt-listchanges: Lettura dei changelog...
Recuperati 97,4 MB in 1min 32s (1.062 kB/s)
(Lettura del database... 
(Lettura del database... 5%
(Lettura del database... 10%
(Lettura del database... 15%
(Lettura del database... 20%
(Lettura del database... 25%
(Lettura del database... 30%
(Lettura del database... 35%
(Lettura del database... 40%
(Lettura del database... 45%
(Lettura del database... 50%
(Lettura del database... 55%
(Lettura del database... 60%
(Lettura del database... 65%
(Lettura del database... 70%
(Lettura del database... 75%
(Lettura del database... 80%
(Lettura del database... 85%
(Lettura del database... 90%
(Lettura del database... 95%
(Lettura del database... 100%
(Lettura del database... 156476 file e directory attualmente installati.)
Preparativi per estrarre .../00-fonts-opensymbol_2%3a102.10+LibO6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di fonts-opensymbol (2:102.10+LibO6.1.5-3+rpi1+deb10u5+rpt1) su (2:102.10+LibO6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../01-ure_6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di ure (6.1.5-3+rpi1+deb10u5+rpt1) su (6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../02-uno-libs3_6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di uno-libs3 (6.1.5-3+rpi1+deb10u5+rpt1) su (6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../03-libreoffice-base-drivers_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-base-drivers (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../04-libreoffice-base_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-base (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../05-libreoffice-calc_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-calc (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../06-libreoffice-impress_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-impress (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../07-libreoffice-draw_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-draw (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../08-libreoffice-gtk3_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-gtk3 (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../09-python3-uno_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di python3-uno (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../10-libreoffice-sdbc-postgresql_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-sdbc-postgresql (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../11-libreoffice-sdbc-hsqldb_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-sdbc-hsqldb (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../12-libreoffice-sdbc-firebird_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-sdbc-firebird (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../13-libreoffice-report-builder-bin_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-report-builder-bin (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../14-libreoffice-math_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-math (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../15-libreoffice-help-it_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-help-it (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../16-libreoffice-help-en-gb_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-help-en-gb (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../17-libreoffice-help-common_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-help-common (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../18-libreoffice-style-tango_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-style-tango (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../19-libreoffice-style-colibre_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-style-colibre (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../20-libreoffice-script-provider-python_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-script-provider-python (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../21-libreoffice-script-provider-js_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-script-provider-js (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../22-libreoffice-script-provider-bsh_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-script-provider-bsh (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../23-libreoffice-report-builder_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-report-builder (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../24-libreoffice-l10n-it_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-l10n-it (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../25-libreoffice-l10n-en-gb_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-l10n-en-gb (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../26-libreoffice-java-common_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-java-common (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../27-libreoffice-common_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-common (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../28-libreoffice-base-core_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-base-core (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../29-libreoffice-avmedia-backend-gstreamer_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-avmedia-backend-gstreamer (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../30-libreoffice_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../31-libreoffice-writer_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-writer (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../32-libreoffice-core_1%3a6.1.5-3+rpi1+deb10u5+rpt1_armhf.deb...
Estrazione di libreoffice-core (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../33-libreoffice-librelogo_1%3a6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-librelogo (1:6.1.5-3+rpi1+deb10u5+rpt1) su (1:6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../34-libreoffice-nlpsolver_0.9+LibO6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-nlpsolver (0.9+LibO6.1.5-3+rpi1+deb10u5+rpt1) su (0.9+LibO6.1.5-3+rpi1+deb10u5)...
Preparativi per estrarre .../35-libreoffice-wiki-publisher_1.2.0+LibO6.1.5-3+rpi1+deb10u5+rpt1_all.deb...
Estrazione di libreoffice-wiki-publisher (1.2.0+LibO6.1.5-3+rpi1+deb10u5+rpt1) su (1.2.0+LibO6.1.5-3+rpi1+deb10u5)...
Configurazione di uno-libs3 (6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di fonts-opensymbol (2:102.10+LibO6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di ure (6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-style-tango (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-style-colibre (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-common (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-core (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-math (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-gtk3 (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-sdbc-postgresql (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-draw (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-java-common (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-base-drivers (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-wiki-publisher (1.2.0+LibO6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-l10n-it (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-avmedia-backend-gstreamer (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-help-common (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-l10n-en-gb (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-sdbc-firebird (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-help-it (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-impress (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-base-core (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di python3-uno (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-script-provider-bsh (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-script-provider-js (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-calc (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-base (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-help-en-gb (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-sdbc-hsqldb (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-writer (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-script-provider-python (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-nlpsolver (0.9+LibO6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-report-builder-bin (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-report-builder (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Configurazione di libreoffice-librelogo (1:6.1.5-3+rpi1+deb10u5+rpt1)...
Elaborazione dei trigger per gnome-menus (3.31.4-3)...
Elaborazione dei trigger per libc-bin (2.28-10+rpi1)...
Elaborazione dei trigger per man-db (2.8.5-2)...
Elaborazione dei trigger per gnome-icon-theme (3.12.0-3)...
Elaborazione dei trigger per shared-mime-info (1.10-1)...
Elaborazione dei trigger per fontconfig (2.13.1-2)...
Elaborazione dei trigger per desktop-file-utils (0.23-4)...
Elaborazione dei trigger per mime-support (3.62)...
Elaborazione dei trigger per hicolor-icon-theme (0.17-2)...
[96mInstalling helper tools ...[90m
Lettura elenco dei pacchetti...
Generazione albero delle dipendenze...
Lettura informazioni sullo stato...
build-essential è già alla versione più recente (12.6).
curl è già alla versione più recente (7.64.0-4+deb10u1).
git è già alla versione più recente (1:2.20.1-2+deb10u1).
unzip è già alla versione più recente (6.0-23+deb10u1).
wget è già alla versione più recente (1.20.1-1.1).
È stato impostato wget per l'installazione manuale.
0 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.
[96mCheck current Node installation ...[0m
[0mNode currently installed. Checking version number.
[0mMinimum Node version: [1mv10.1.0[0m
[0mInstalled Node version: [1mv10.15.3[0m
[92mNo Node.js upgrade necessary.[0m
[96mCheck current NPM installation ...[0m
[0mNPM currently installed. Checking version number.
[0mMinimum npm version: [1mV6.0.0[0m
[0mInstalled npm version: [1mV6.4.1[0m
[92mNo npm upgrade necessary.[0m
[96mCloning MagicMirror ...[90m
[92mCloning MagicMirror Done![90m
package.json update for armv6l completed ok
[96mInstalling dependencies ...[90m
[91mUnable to install dependencies! [90m

**Comment by Smiley-94** [comment]
[install.log](https://github.com/sdetweil/MagicMirror_scripts/files/4464583/install.log)

**Comment by sdetweil** [comment]
cool, thanks

do this
```
cd ~/MagicMirror
sudo npm install -g npm 
npm -v
npm install --only=prod
```
let me know how it goes.. looks like npm is too far downlevel..  but why on your system I can't tell

did u install npm manually? before running my script?

**Comment by Smiley-94** [comment]
I actually tried to install with the default procedure... and since it gave me that error I tried with yours

**Comment by Smiley-94** [comment]
again the same error:


pi@P0SmartMirror:~/node-v10.15.3-linux-armv6l $ cd ~/MagicMirror
pi@P0SmartMirror:~/MagicMirror $ udo npm install -g npm 
-bash: udo: comando non trovato
pi@P0SmartMirror:~/MagicMirror $ sudo npm install -g npm 
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.14.4
added 74 packages from 21 contributors, removed 26 packages and updated 87 packages in 213.212s
Annullato
pi@P0SmartMirror:~/MagicMirror $ npm -v
6.14.4
Annullato
pi@P0SmartMirror:~/MagicMirror $ npm install --only=prod
npm WARN deprecated time-grunt@2.0.0: Deprecated because Grunt is practically unmaintained. Move on to something better. This package will continue to work with Grunt v1, but it will not receive any updates.
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated webdriverio@4.14.4: outdated version, please use @next
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

> console-stamp@0.2.9 postinstall /home/pi/MagicMirror/node_modules/console-stamp
> node ./msg.js

Attention
    Console-stamp version 3.0.0 Release Candidate is out. Install by using the tag '@next'. NB: Breaking changes.
    For more details goto: https://www.npmjs.com/package/console-stamp/v/next

Aborted
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! console-stamp@0.2.9 postinstall: `node ./msg.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the console-stamp@0.2.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-04-11T12_44_05_149Z-debug.log
Annullato

**Comment by sdetweil** [comment]
ok, looking,, thx

**Comment by sdetweil** [comment]
ok, my install worked, but it was fresh.. 

do this
```
cd ~/MagicMirror
rm -rf node_modules
rm package-lock.json
npm install --only=prod
```

please advise

**Comment by Smiley-94** [comment]
I can do a fresh install too if you think I'll help

**Comment by sdetweil** [comment]
no, lets do this first.. see if we can recover from the failure

**Comment by Smiley-94** [comment]
done, it just failed again on the same spot... I'll try a clean install in a while

**Comment by sdetweil** [comment]
ok, just do

cd ~
mv MagicMiror MagicMirror.old

then run the install script
thats what I just did on my pi 0 buster

**Comment by Smiley-94** [comment]
it did not work but a fresh install did the job, now I have it working even if during instal it gave me some errors

**Comment by sdetweil** [comment]
@Smiley-94  great!... can u show me the ~/install.log again.. like to understand the errors you encountered

**Comment by sdetweil** [comment]
I'm going to close this

**Comment by Smiley-94** [comment]
Sorry that i have not answered, i’m away for work for a couple of days and i did not saw your message... i’ll send it to you as soon as i get home
