### ISSUE TITLE
black screen only mouse pointer after boot

### ISSUE THREAD

**Issue by sabres7th** [sdetweil/MagicMirror_scripts#30]
raspberry pi 2 b+ installed magicmirror os and afterthe boot no config settings ask showblack screen withmouse pointer no commands or anything have effect cant cclose or edit anything....

**Comment by sdetweil** [comment]
trying to be clear. 

you installed the raspi operating system
using the full desktop image
and used my script to install MagicMirror

can you attach the install.log file from the users (pi) home folder.

**Comment by sabres7th** [comment]
sorry i guess im in the wrong place no it is a os withit already iinstalled on it and i am having this problem, i would use your script but do in need other programs to edit  where do i find thos to install links would be very helpful

**Comment by sdetweil** [comment]
my scipt is for installing on the base Raspi OS.  or mac, or linux, 
raspi os, downloaded from here 
https://www.raspberrypi.org/software/operating-systems/
top item, full desktop

this is the MagicMirrorOS github page 
https://github.com/guysoft/MagicMirrorOS

**Comment by sabres7th** [comment]
Yes this is it the system shows the colors and the Raspberry Pi splash
screen just some type of check or type of thing it's all loaded up then
goes immediately to a black screen where I only see the mouse I'm unable to
use any controls afterwards except move the mouse No commands or any
shortcuts or specific Keys seem to have any reaction

**Comment by sdetweil** [comment]
sorry, no idea.. never tried MMOS

**Comment by sabres7th** [comment]
I learned how to install the script but after I got done making the sh file
I believe for yours it said I needed some other programs installed already
appreciate your attention would you be able to just to tell me where to get
all the programs I need so I can just run the script just like yon need
nodes 10 or not python but another that starts with a p where do I find
these please, thank you

**Comment by sabres7th** [comment]
I have the full raapian  image on One SD card and then the Raspberry Pi OS
on another SD card I have your script for the raspian image.

**Comment by sdetweil** [comment]
all you have to do is cut/paste the command from the git repo online into a command shell window on raspi, and the script does everything.. gets git, any tools needed, node, npm, everything

**Comment by sabres7th** [comment]
I will try right now again ty for the help

**Comment by sdetweil** [comment]
the instructions on my repo say 
```
to execute the install script, cut/paste this line into the terminal window on your device (I can't say PI, cause it works in a lot of other places too)
```

**Comment by sabres7th** [comment]
I see give a few minutes.

**Comment by sabres7th** [comment]
Looks like it's working I think it said here for 10 minutes and then I
aborted last night and then tried moving on to something else... I assume
with pi2b+ and a 400mbps Ethernet download speed this will still take 20
mins, I assume it is processing?

**Comment by sdetweil** [comment]
yes, it needs to get stuff... sometimes takes 2 minutes and sometimes an hour.. crazy..

**Comment by sabres7th** [comment]
My pie seems slower than most but for $15 I had to try it and take on this
project with the pie 2 b+, can you tell me the newest pie can I just
transfer the SD card into it and run it if I upgrade?

**Comment by sdetweil** [comment]
pi4 is the latest

I don't know if the card as built for pi2 will work unchanged in pi 4, bit probably.

I have pi 0,3 and 4 here

**Comment by sdetweil** [comment]
did u resolve any issues?

**Comment by sabres7th** [comment]
Yes it works completely I thought I sent you a video thank you so much !

**Comment by bachoo786** [comment]
I am having the same issue black screen with only mouse cursor

**Comment by sdetweil** [comment]
yes  look at the pm2 logs

pm2 logs --lines=100

search for module not found

**Comment by sabres7th** [comment]
What os are you using?

**Comment by bachoo786** [comment]
Ok I just did npm install and seems to be working now. I am using rpi4 and its the latest raspbian buster.
