### ISSUE TITLE
Not so magicmirror

### ISSUE THREAD

**Issue by sabres7th** [sdetweil/MagicMirror_scripts#31]
![PXL_20210627_204318560](https://user-images.githubusercontent.com/82855610/123558912-ef846780-d766-11eb-8043-503a955f9a7d.jpg)
![PXL_20210627_204330004](https://user-images.githubusercontent.com/82855610/123558915-f0b59480-d766-11eb-938d-8ec620b895a2.jpg)
Been going this for 4 days need some help...please links please or just send me a link for magicmirror Verision one I can find it anywhere, first it was arm6 not supported then, nodes Verision the npm version then it was electron the it says uuid .. enough help please.

**Comment by sabres7th** [comment]
Also I complains of har-validator 5.1.5 not supported for some other part of the setup for a package

**Comment by sdetweil** [comment]
just copy paste the one line into a terminal window on pi, the doc says copy one line

```
Install MagicMirror
raspberry.sh is the installation script, upgraded from the core package
to execute the install script, cut/paste this line into the terminal window on your device (I can't say PI, cause it works in a lot of other places too)
```

what kind of pi?

turn on SSH in pi config (upper left menu, preferences)

then u can use an SSH window on your windows or mac machine to do all the commands, and cut/paste results..

**Comment by sdetweil** [comment]
ignore the messages
 libraries that we use, use them and nothing we can do about it.  

don't run audit fix
makes more trouble than it fixes

**Comment by sabres7th** [comment]
Ok what should do exactly to start this?

**Comment by sabres7th** [comment]
I have no Idea where I am at right now, or how to get this to start.

**Comment by sabres7th** [comment]
#!/bin/bash
  # use bash instead of sh
[ -f ./untrack-css.sh ] && ./untrack-css.sh

if grep docker /proc/1/cgroup -qa; then
  # if running in docker, only start electron

  electron js/electron.js $1;
else
  # not running in docker

  if [ -z "$DISPLAY" ]; then #If not set DISPLAY is SSH remote or tty
    export DISPLAY=:0 # Set by default display
  fi
  # get the processor architecture
  arch=$(uname -m)
  false='false'
  true='true'

  # get the config option, if any
  # only check non comment lines
  serveronly=$(grep -v '^[[:blank:]]*//'  config/config.js | grep -i serveronly: | awk -F: '{print tolower($2)}' | tr -d ,\"\'\\r | sed -e 's/^[[:space:]]*//')
  # set default if not defined in config
  serveronly=${serveronly:-false}
  # check for xwindows running
  xorg=$(pgrep Xorg)
  if [ "$xorg." == "." ]; then
     # check for x on Lubuntu
     xorg=$(pgrep X)
  fi
  #check for macOS
  mac=$(uname)
  el_installed=$true
  if [ ! -d node_modules/electron ]; then
    el_installed=$false
  fi
  #
  # if the user requested serveronly OR
  #    electron support for armv6l has been dropped OR
  #    system is in text mode
  #
  if [ "$serveronly." != "false." -o  "$arch" == "armv6l" -o "$arch" == "i686" -o $el_installed == $false  ]  ||  [ "$xorg." == "." -a $mac != 'Darwin' ]; then

      t=$(ps -ef | grep  "node serveronly" | grep -m1 -v color | awk '{print $2}')
      if [ "$t." != '.' ]; then
        sudo kill -9 $t >/dev/null 2>&1
      fi
    # if user explicitly configured to run server only (no ui local)
    # OR there is no xwindows running, so no support for browser graphics
    if [ "$serveronly." == "true." ] || [ "$xorg." == "." -a $mac != 'Darwin' ]; then
      # start server mode,
      node serveronly
    else
      # start the server in the background
      # wait for server to be ready
      # need bash for this
      exec 3< <(node serveronly)

      # Read the output of server line by line until one line 'point your browser'
      while read line; do
         case "$line" in
         *point\ your\ browser*)
            echo $line
            break
            ;;
         *)
            echo $line
            #sleep .25
            ;;
         esac
      done <&3

      # Close the file descriptor
      #exec 3<&-

      # lets use chrome to display here now
      # get the server port address from the ready message
      port=$(echo $line | awk -F\: '{print $4}')
      # start chromium
      echo "Starting chromium browser now, have patience, it takes a minute"
      # continue to spool stdout to console
      tee <&3 &
			if [ $mac != 'Darwin' ]; then
        b="chromium"
        if [ $(which $b). == '.' ]; then
          b='chromium-browser'
        fi
        if [ $(which $b). != '.' ]; then
				  "$b" -noerrdialogs -kiosk -start_maximized  --disable-infobars --app=http://localhost:$port  --ignore-certificate-errors-spki-list --ignore-ssl-errors --ignore-certificate-errors 2>/dev/null
        else
          echo "Chromium_browser not installed"
        fi
			else
			  open -a "Google Chrome" http://localhost:$port --args -noerrdialogs -kiosk -start_maximized  --disable-infobars --ignore-certificate-errors-spki-list --ignore-ssl-errors --ignore-certificate-errors 2>/dev/null
			fi
      exit
    fi
  else
    # we can use electron directly
    node_modules/.bin/electron js/electron.js $1;
  fi
fi

**Comment by sabres7th** [comment]
Did this and now I have a black screen
![Uploading PXL_20210627_224746353.MP.jpg…]()

**Comment by sabres7th** [comment]
After black screen that would not go away and a restart of the pie we are  ack to this game again
![PXL_20210627_225938318 MP](https://user-images.githubusercontent.com/82855610/123562008-f5d00f00-d779-11eb-91f7-18606114b231.jpg)

**Comment by sdetweil** [comment]
what pi is this?   my script is supposed to detect this and setup for split mode...

to run my script, you copy paste the one line 
```
bash -c  "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/raspberry.sh)"
```
into your terminal window

show me the install.log in the user home folder..

when u have the black screen, minimize the window,,
alt-spacebar, n

or stop MM, with alt-q (if started with npm start)..

**Comment by sabres7th** [comment]
used your script specifically and nothing else after you got back to me
with the fresh install after the black screen I tried running it again and
it wouldn't detect electron so I'm reinstalling electron currently I did
try and find this log file and I wasn't able to find any log file in any
folder in the MM directory.

**Comment by sdetweil** [comment]
~/install.log

which means my script did not run..

you MUST use the bash  etc to make the script RUN... 

IF the MagicMirror folder is already there, then the script exits, as it is a NEW install only..
you can rename your existing MagicMirror folder out of the way 
in linux the rename command is mv

**Comment by sabres7th** [comment]
Okay so I just use the bash command when I run your script inside the
command line... Okay I'll I'll do this again but I see all the folders and
all the modules..

**Comment by sdetweil** [comment]
u copy paste exactly what i posted.. the entire text, front to back.. 

its done like this so you don't have to know anything... just copy paste one line

**Comment by sabres7th** [comment]
Well I gave it another full 8 hour day for the third day even tried your
U-Haul URL again one last time the reinstall all's I'm getting is 404 errors

**Comment by sdetweil** [comment]
404 is not found.

so it sounds like a networking problem or dns server problem

**Comment by sabres7th** [comment]
I have magicmirror 2 installed but it won't open with out electron, I had to get it from a. Zip download, what do I do now?
![Uploading PXL_20210628_032256619.jpg…]()

**Comment by sdetweil** [comment]
sorry. no idea. never done that. 

my script sets up for chromium over mm in server mode when electron is not available

**Comment by sabres7th** [comment]
Server mode worked! Good enough for me ,the weather does not load but I
assume I would have to adjust something? Also can I still add modules or a
photo to it somehow?

**Comment by sdetweil** [comment]
yes  just do the normal process. we've only found a couple modules that have trouble in server mode. 

weather u have to get an API key from the provider you select.

**Comment by sabres7th** [comment]
Thank you for your response, yes I was worries about the weather I checked
and it seemed to have the config correct for my city I will look into this
key. I have MMM wallpaper it installed the folder under the modules but I
don't see anything inside this folder I'm trying to put a background up do
you know the simplest way about going about this?

**Comment by sabres7th** [comment]
Thanks, I'll check it out.

**Comment by sabres7th** [comment]
![PXL_20210629_082704280](https://user-images.githubusercontent.com/82855610/123763914-476bbd00-d892-11eb-974d-85975f6e62f3.jpg)
I have the information for my modules all ready to go for the Js file I'm having problems editing it though

**Comment by sabres7th** [comment]
![PXL_20210629_083001260](https://user-images.githubusercontent.com/82855610/123764371-b9440680-d892-11eb-94d8-2f85135f4e83.jpg)

**Comment by sabres7th** [comment]
![PXL_20210629_083011744](https://user-images.githubusercontent.com/82855610/123764412-c19c4180-d892-11eb-96cb-a661aee9988e.jpg)
Mmmm noob help please

**Comment by sdetweil** [comment]
the editors on pi are gedit, or command line vi and nano 
read this
https://forum.magicmirror.builders/topic/4231/how-to-add-modules-for-absolute-beginners
and this 
https://forum.magicmirror.builders/topic/4528/how-to-create-a-working-config-for-absolute-beginners

u might be interested in my new module that makes editing of the config a thing of the past (after adding my module of course!)
https://github.com/sdetweil/MMM-Config

**Comment by sabres7th** [comment]
Have it all set up just won't take a photo from a local directory... Trying
to host on flicker, ty for the help.

**Comment by sdetweil** [comment]
the MagicMirror web server for self hosting root is the MagicMirror folder, so everything has to be relative to that
cannot be OUTSIDE the MM folder..

http://localhost:port/modules/....... is ok

file:///home/pi/somefolder/someotherfolder  is NOT ok

**Comment by sabres7th** [comment]
Ohhhhhh ok so I just put the file in that folder and then reference it in
the configuration

**Comment by sdetweil** [comment]
ImagePhotos ONLY takes from the uploads folder
modules/MMM-ImagesPhotos/uploads

you can link it to another folder using the ln command

so it looks like the folder is there, but its actually from another place..

I do this all the time on every machine.. I have a server for my photographs, which I mount on the pi, then link the uploads folder to a folder on the shared drive

**Comment by sabres7th** [comment]
I don't have this folder imagine uploads ...

**Comment by sabres7th** [comment]
Idk I put it there, does not seen to work wallpapers just has .Js files in
there.

**Comment by sdetweil** [comment]
I was just saying for THAT module, MMM-ImagesPhotos, it uses the uploads folder 
I don't know about others..

if u installed the MMM-ImagePhotos module it would create that folder in its folder

**Comment by sabres7th** [comment]
Oh I will try this then I will search I looked at your page I did not see
it .

**Comment by sdetweil** [comment]
https://github.com/sdetweil/MMM-ImagesPhotos

**Comment by sabres7th** [comment]
Need to resize photo and calander if your awake it would be css for this
yes ? Where can I adjust?

**Comment by sabres7th** [comment]
![Screenshot_20210629-194004](https://user-images.githubusercontent.com/82855610/123881274-5abe6d00-d912-11eb-992f-0167797f302e.png)
So I like how the greetings are on top of the picture I'd like to do this for the top I'm not sure where the setting is for the always on top or something for each module and then also I'd like to resize the calendar with this be done through CSS I appreciate your help with everything you manage to provide me with information sufficiently

**Comment by sdetweil** [comment]
text on top is z-index,,, xis left right, y is up down, z is in out,,, + is towards u - is away from you 0 is the middle.

the css design is a stack.    css/main.css is at the bottom,  module provided css is next on top, and css/custom.css is on top

u can override any previous definition in custom.css
(if not there just do touch css/custom.css to create the file)

to target a modules content,
their module name is used as the class of the outer container

so 
.modulename  .class or whatever { 
  styles
}

u can learn what u want to do in the dev console 
read this
https://forum.magicmirror.builders/topic/14862/help-with-a-couple-css-issues?_=1624967283818

one thing learned since then, you can copy paste the contents of the style window (top right in the screen shots) 
and paste that into you css entry.. 

this is the css selectors cheatsheet I use
https://www.w3schools.com/cssref/css_selectors.asp

. means classname
no dot means an html element name (div, button, ....)


there is no simple change this one thing and it will all be better..
every author does their own thing, some provide classes & styles, some provide config parms to address the styles they know about
some do nothing
some document
some don't..
so, no two modules are alike. (unless  they are from the same vendor)

**Comment by sabres7th** [comment]
Okay I got the editing and values so basically I do the HTML Explorer look
at the CSS elements and then I can modify it there in the scripting copy it
now do I copy the script from the web page after I edit it in the viewer
and save it to a file in the directory somewhere to apply these changes?

**Comment by sabres7th** [comment]
So I go here to edit ? Then save changes?

**Comment by sdetweil** [comment]
you go there to experiment. nothing is saveable in the dev window

**Comment by sabres7th** [comment]
Ok where can I get at the numbers to experiment I am not seeing css pixels
sizes for modules there

**Comment by sabres7th** [comment]
Ah ok I think I got it ty.

**Comment by sdetweil** [comment]
the stack of styles is listed on the right.main.css styles at the bottom, the edit window at the top of the stack.

it tells u where each style came from

**Comment by sabres7th** [comment]
I got something like this going on kind of exploring it's not really
highlighting anything this is it runs really really slow

**Comment by sabres7th** [comment]
?

**Comment by sdetweil** [comment]
click the elements tab

**Comment by sabres7th** [comment]
It's really low can I just edit the CSS Main and then save this changed
file to the custom CSS I don't see a folder for custom CSS though where
would I put this?

**Comment by sdetweil** [comment]
I told you already exactly where it is

**Comment by sabres7th** [comment]
Ok, I'll check it out.

**Comment by sabres7th** [comment]
Okay I went ahead and reduced all the text size in line spacing by 75% I'll
let you know how it turns out thank you for your help

**Comment by sabres7th** [comment]
Ok I can adjust the text size and tune it in and to think the image I would
adjust thought the image photo module correct? What do you think would be
best? To reduce he image size by 20%  also I need to adjust the letter
spacing for the greeting it uses some +/- number system?

**Comment by sdetweil** [comment]
depends on what you want to do. I run my images photos fullscreen-behind

**Comment by sabres7th** [comment]
Hmmm is that in the module configuration correct, thank you for your help
and patience again as well

**Comment by sdetweil** [comment]
there are a bunch of positions for modules.

**Comment by sabres7th** [comment]
So you're talking about module positions not the specific module for image
photos settings how can I get this background image to not be on top and to
be on the bottom layer please

**Comment by sdetweil** [comment]
set the module position to fullscreen_below

or set the image style with zindex:-1;

**Comment by sdetweil** [comment]
did you get it solved?
