### ISSUE TITLE
Suggestion: Progress/movement indicator...

### ISSUE THREAD

**Issue by BKeyport** [sdetweil/MagicMirror_scripts#32]
Sam, would it be possible to indicate on screen some sort of progress indicator or a movement indicator? 

The installer taking forever on a box with no disk activity light is *quite* annoying. :)

**Comment by sdetweil** [comment]
wanna try it? 

bash -c  "$(https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/with_progress_bar/raspberry.sh)"

**Comment by BKeyport** [comment]
Works great when I put together the right command. 😉 

(You forgot the curl part of the statement)

**Comment by sdetweil** [comment]
sorry, I cut pasted from the real one, guess I cut off the start when I pasted. Sorry

**Comment by sdetweil** [comment]
added to latest update
