### ISSUE TITLE
Is there a script for mac?

### ISSUE THREAD

**Issue by Mahieedaboss** [sdetweil/MagicMirror_scripts#4]
I need it because raspberry pi3 couldnt instal ffmpeg

**Comment by sdetweil** [comment]
there is no special scrip for mac.. all the scripts work on mac as well..

i just loaded ffmped on my pi without problem

sudo apt-get install ffmpeg

brew is a mac thing

**Comment by sdetweil** [comment]
closing ffmpeg was installed
