### ISSUE TITLE
upgrade-script.sh node running check enhancement

### ISSUE THREAD

**Issue by FrankBlackMG** [sdetweil/MagicMirror_scripts#41]
upgrade-script.sh line 118 has:

`if pgrep "node" > /dev/null; then`

I happen to have nomachine installed on my pi4 and it has a process named nxnode. The pgrep command was finding it and aborting. I changed the script to:

`if pidof "node" > /dev/null; then`

and it worked fine. I supposed you could do this for the npm check as well. It's not bullet-proof but it worked for my case.

**Comment by sdetweil** [comment]
thanks.. didn't know about pidof
