### ISSUE TITLE
Windows installation throws error

### ISSUE THREAD

**Issue by MichlF** [sdetweil/MagicMirror_scripts#42]
I tried to install MM following the documentation on how to install on Windows (including the special steps with respect to Windows installations that all ran fine no matter whether I executed them before or after the error). However when running `npm install` inside the MagicMirror folder, tan error is thrown repeatedly at the same stage:
```
> magicmirror@2.18.0 prepare
> [ -f node_modules/.bin/husky ] && husky install || echo no husky installed.

Der Befehl "[" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
no husky installed.
```
The error message losely translates to "The command "[" is either spelled incorrectly or could not be found."
Following this error I am getting an oddly reassuring... :

```
up to date, audited 757 packages in 2s

66 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

... but magic mirror won't start:

```
C:\MM\MagicMirror>npm run start

> magicmirror@2.18.0 start
> node_modules/.bin/electron js/electron.js

Der Befehl "node_modules" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```

I am running node.js 16.13.1 and npm version 8.1.2 on Windows 10 latest version.

Is this a bug or am I doing something wrong here?

Thanks for any hint!

**Comment by sdetweil** [comment]
my stuff doesn't work on windows

have to do manual install and the extra steps.

oh, I see they have screwed up the extra steps too!! ( husky)


u have to install mode and npm before MagicMirror.

u will have to open an issue on the MagicMirror GitHub page. I don't have any control over that

**Comment by sdetweil** [comment]
fixed by changing package.json  start line like this
```
"start": "node_modules\\.bin\\electron js\\electron.js",
```
