### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by misbahbhutto** [sdetweil/MagicMirror_scripts#43]
pi@raspberrypi:~/MagicMirror $ npm install
npm ERR! code EAI_AGAIN
npm ERR! syscall getaddrinfo
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/yazl/-/yazl-2.5.1.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-01-12T07_58_19_368Z-debug.log

**Comment by sdetweil** [comment]
this is a networking issue. nothing I can do.
