### ISSUE TITLE
ScreenSaver back on

### ISSUE THREAD

**Issue by DennisEJ** [sdetweil/MagicMirror_scripts#44]
I'd like to turn the screensaver back on  until I can get to the PIR install.  How can I turn the screensaver back on?
Thanks
Dennis
(I hope I'm asking in the correct place.)  If not I apologize.

**Comment by sdetweil** [comment]
use the deskop menu, top left, preferences, display, blanking,

**Comment by DennisEJ** [comment]
Thanks Sam

**Comment by DennisEJ** [comment]
That worked. Thanks again
