### ISSUE TITLE
unable to install dependencies

### ISSUE THREAD

**Issue by Slaton87** [sdetweil/MagicMirror_scripts#45]
Hi,
I tried running this on my pi and at the end it is unable to install dependencies. Any help on fixing this would be greatly appreciated.

From terminal:
Installing dependencies ...
bash: line 412: npm: command not found
Unable to install dependencies! 

Install Log:
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.9).
curl is already the newest version (7.74.0-1.3+deb11u1).
git is already the newest version (1:2.30.2-1).
unzip is already the newest version (6.0-26).
wget is already the newest version (1.21-1+deb11u1).
wget set to manually installed.
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 nodejs : Depends: libnode72 (= 12.22.5~dfsg-2~11u1) but it is not going to be installed
[96mUpdating packages ...[90m
Hit:1 https://deb.nodesource.com/node_16.x bullseye InRelease Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease Hit:3 http://archive.raspberrypi.org/debian bullseye InRelease Reading package lists...
apt-get update  completed ok
apt-get upgrade  started
apt upgrade result =rc=127 
[96mCheck current Node installation ...[0m
[0mNode currently installed. Checking version number.
forcing low Node version
[0mMinimum Node version: [1mv16.9.1[0m
[0mInstalled Node version: [1mV1.0.0[0m
[96mNode should be upgraded.[0m
[96mInstalling Node.js ...[90m
Node release info = ## Installing the NodeSource Node.js 16.x repo... ## Populating apt-get cache... + apt-get update Hit:1 https://deb.nodesource.com/node_16.x bullseye InRelease Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease Hit:3 http://archive.raspberrypi.org/debian bullseye InRelease Reading package lists... ## Confirming "bullseye" is supported... + curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/bullseye/Release' ## Adding the NodeSource signing key to your keyring... + curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null ## Creating apt sources list file for the NodeSource Node.js 16.x repo... + echo 'deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x bullseye main' > /etc/apt/sources.list.d/nodesource.list + echo 'deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x bullseye main' >> /etc/apt/sources.list.d/nodesource.list ## Running `apt-get update` for you... + apt-get update Hit:1 https://deb.nodesource.com/node_16.x bullseye InRelease Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease Hit:3 http://archive.raspberrypi.org/debian bullseye InRelease Reading package lists... ## Run `sudo apt-get install -y nodejs` to install Node.js 16.x and npm ## You may also need development tools to build native addons: sudo apt-get install gcc g++ make ## To install the Yarn package manager, run: curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list sudo apt-get update && sudo apt-get install yarn
node version is node: error while loading shared libraries: libnode.so.72: cannot open shared object file: No such file or directory
[92mNode.js installation Done! version=[0m
[96mCheck current NPM installation ...[0m
[93mnpm is not installed.[0m
[96mInstalling npm ...[90m
Reading package lists...
Building dependency tree...
Reading state information...
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 nodejs : Depends: libnode72 (= 12.22.5~dfsg-2~11u1) but it is not going to be installed
 npm : Depends: node-gyp (>= 3.6.2~) but it is not going to be installed
upgrading npm to latest
[92mnpm installation Done! version=V[0m
[96mCloning MagicMirror ...[90m
[92mCloning MagicMirror Done![90m
[96mInstalling dependencies ...[90m

[91mUnable to install dependencies! [90m

I also tried the recommended: apt --fix-broken install

**Comment by sdetweil** [comment]
looks like u might be using the lite version

MUST be full w desktop

**Comment by Slaton87** [comment]
Thanks! I’ll redownload the program on the sd card and give it a shot. My 8yr old is wanting to try and learn about this stuff so that means I am too lol.

**Comment by sdetweil** [comment]
@Slaton87   did you resolve this?

**Comment by sdetweil** [comment]
closing due to lack of response.. if still a problem reopen
