### ISSUE TITLE
102730091 ms: Mark-sweep 881.5 (983.0) -> 880.4 (983.3) MB, 6928.0 / 0.5 ms  (average mu = 0.346, current mu = 0.311) allocation failure scavenge might not succeed

### ISSUE THREAD

**Issue by Fredi009sg** [sdetweil/MagicMirror_scripts#46]
Got this after a while. How can i fix it ?

**Comment by sdetweil** [comment]
no idea, not part of my package.. it just does install

**Comment by sdetweil** [comment]
closing as not part of installer script issues.. open on MagicMirror issues page if still occurring
