### ISSUE TITLE
Not sure if Issue or not

### ISSUE THREAD

**Issue by Plainbroke** [sdetweil/MagicMirror_scripts#48]
Hey Sam,
I get the following when I installed MagicMirror with your script and also when I tried to sudo apt update.

W: Failed to fetch https://packagecloud.io/Keymetrics/pm2/debian/dists/bullseye/InRelease  429  Too Many Requests [IP: 54.215.170.165 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.

Jeff

**Comment by sdetweil** [comment]
@Plainbroke 
>So if I send a empty file ended at night to the motion folder in MMM-SleepWake that triggers the timer in config.js to blank screen?
and then in the morning send empty file detected to the same motion folder in MMM-SleepWake it should turn the modules back on.

correct

if you just call the script MMM-SleepWake/external_motion 
with started or ended
it will do the right thing

**Comment by sdetweil** [comment]
no.. BUT, I have a repo that creates backup and restore

https://github.com/sdetweil/MagicMirror-backup-restore

it saves config.js, custom.css

and then finds and saves all the links to the installed modules.

so 3 small files.

restore copies config.js, and custom.css to the new MagicMirror folder , and the installs all the modules in the saved list

additionally  it creates a git repo that you can push to GitHub.and tags each backup with it's date..  so you could restore a particular instance.

each command supports --help 

this installs outside the MagicMirror folder

**Comment by sdetweil** [comment]
ok, 1st message trouble with backup custom.css and config.js

by default the backup script uses 
from $HOME/MagicMirror
to  $HOME/MM_backup 

you can change those with the -s and -b parms

as a test, do 
```
cd ~/MagicMirror-backup-restore
bash -x mm_backup.sh >somefile.txt 2>&1
```
after it ends (quickly and quitely) 
nano somefile.txt 

you should see this at the top 
```
+ base=/home/sam/MagicMirror
+ saveDir=/home/sam/MM_backup
++ uname -s
+ mac=Linux
+ '[' Linux == Darwin ']'
+ cmd=readlink
+ msg_prefix=updating
+++ readlink -f ./mm_backup.sh
++ dirname /home/sam/MagicMirror-backup-restore/mm_backup.sh
+ script_dir=/home/sam/MagicMirror-backup-restore
+ getopts hs:b: opt
+ '[' '!' -d /home/sam/MM_backup ']'
+ '[' '!' -d /home/sam/MM_backup/.git ']'
+ repo_list=/home/sam/MM_backup/module_list
+ echo updating folder /home/sam/MM_backup
updating folder /home/sam/MM_backup
+ cp -p /home/sam/MagicMirror/config/config.js /home/sam/MM_backup
+ cp -p /home/sam/MagicMirror/css/custom.css /home/sam/MM_backup
```

with your home folder (/home/pi?)  instead of mine (/home/sam)

of course, if the magicmirror folder is a different name than oops.. 
need to specify the -s $HOME/????  whatever the folder name is

and YOU have to run backup EVERY time you change anything.. (but it will keep a date ordered list  of changes) 

sort.. not really.. the sort command sorts them my author userid..

**Comment by sdetweil** [comment]
message with >I am curious if I can backup to the GitHub some way with this backup restore module of yours?

absolutely

create a repo on your github home page , click repositories in the top bar,
then new
then give it a name 

you will get a list of commands 

```
…
or push an existing repository from the command line
```
back on the pi do them (copy paste) 
```
git remote add origin https://github.com/userid/reponame.git
git branch -M main
git push -u origin main
```

every backup is marked as a collection of changed files together, under a date/time tag 
```
(base) sam@sams:~/MM_backup$ git tag 
21-Aug-2022-19-11-10
21-Aug-2022-19-11-11
21-Aug-2022-19-13-04
(base) sam@sams:~/MM_backup$ 
```
then back on the pi 

u can checkout a tag and make a new branch with those files.. 
git checkout tagname  -b branchname
```
git checkout 21-Aug-2022-19-11-11 -b new-f
Switched to a new branch 'new-f'
```

then to restore, just run mm_restore, with -b pointing to this folder ( if u git cloned it from github, just like a module)

**Comment by Plainbroke** [comment]
This worked and looks like yours only mine says pi instead of sam.

Jeff Burdick

**Comment by sdetweil** [comment]
really about backup/restore which is improved, closing here
