### ISSUE TITLE
Magic Mirror installation broken when running upgrade script

### ISSUE THREAD

**Issue by justinreimer** [sdetweil/MagicMirror_scripts#49]
My magic mirror project seems to have stopped working after running the upgrade script. Bellow is the list of steps I've taken so far.

ran `bash -c  "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/upgrade-script.sh)"`
	- Seemed fine

ran `bash -c  "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/upgrade-script.sh)" apply`
	- Was told I had to disable node processes to upgrade node

ran `pm2 stop MagicMirror`

ran `bash -c  "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/upgrade-script.sh)" apply` again

hung at line `npm WARN invalid config only="prod --omit=dev --no-audit --no-fund --no-update-notifier" set in command line options npm WARN invalid config Must be one of: null, prod, production`

Eventuall had to end process

ran `pm2 restart MagicMirror`

mirror no longer starts up

ran `bash -c  "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/upgrade-script.sh)" apply` again
	- says everything is up to date
	
tried to start from scratch by running install script `bash -c  "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/raspberry.sh)"`
        - says MagicMirror is already installed

**Comment by justinreimer** [comment]
Here is my upgrade log if that helps
[upgrade.log](https://github.com/sdetweil/MagicMirror_scripts/files/9294280/upgrade.log)

**Comment by justinreimer** [comment]
Not sure if this is just an issue with pm2, or if the magic mirror update is incomplete and causing startup to fail.

**Comment by sdetweil** [comment]
Ok, looks like npm has removed the option of --only=prod.. 

i fixed the scripts.. 
try again 

also, you ONLY run upgrade when move between MM versions (a new release every 90 days) ...

**Comment by sdetweil** [comment]
correct, install is new..  from nothing..

so rename the MagicMirror folder or delete it

to 'upgrade' the current release  , use force
instead of apply

**Comment by justinreimer** [comment]
Yep, running the upgrade script with `force` worked. Had to remove and reinstall the `electron` node module as well, but seems to be working now. Thanks

**Comment by sdetweil** [comment]
can u post the installers/upgrade.log

electron has troubles sometimes, not sure why

**Comment by sdetweil** [comment]
thanks they really messed up the options syntax..  

fixed the scripts again

**Comment by justinreimer** [comment]
No problem. Thanks for the quick updates

**Comment by sdetweil** [comment]
fixed again
