### ISSUE TITLE
Trying to install MM from script on RPi Zero 2

### ISSUE THREAD

**Issue by poopyurinal** [sdetweil/MagicMirror_scripts#51]
Hi, I'm trying to install MM on a brand new RPi OS 32-bit install on a Zero 2 model. I've done 2 new installs that hit the same snag. Looks like an issue with dependencies. I am still a NOOB, have a bit of experience but can't troubleshoot this one. Is this expected with a  Zero 2 install? Can it be fixed? Thanks!
[install.log](https://github.com/sdetweil/MagicMirror_scripts/files/9313286/install.log)

**Comment by poopyurinal** [comment]
My issue is the same as reported in #52 by thatguyinoz, which looks like it was a purposeful change a couple days ago. Appreciate any effort to look into this!

**Comment by sdetweil** [comment]
testing fix now

**Comment by sdetweil** [comment]
I have reverted the last change... it should work now.. 

the other platform I was testing on has some other problem..

**Comment by poopyurinal** [comment]
Working now, thank you!
