### ISSUE TITLE
npm ERR! Invalid tag name "omit=dev" of package "omit=dev"

### ISSUE THREAD

**Issue by thatguyinoz** [sdetweil/MagicMirror_scripts#52]
Hi
There is a minor typo in the installer script at line 417 .
This throws the error:
 npm ERR! Invalid tag name "omit=dev" of package "omit=dev": Tags may not have any characters that encodeURIComponent encodes.
it seems there is an extraneous space " " in the string
Line 417:  JustProd="-- omit=dev --no-audit --no-fund --no-update-notifier"
should be  JustProd="--omit=dev --no-audit --no-fund --no-update-notifier"
cheers and thanks for all your hard work :-)

**Comment by sdetweil** [comment]
fixed, try again

**Comment by thatguyinoz** [comment]
All good now :-)
thanks
