### ISSUE TITLE
Fixuppm2.sh creates a file named 0 

### ISSUE THREAD

**Issue by OldSunGuy** [sdetweil/MagicMirror_scripts#57]
I ran ``` fixuppm2.sh ``` and noticed a file named ``` 0 ``` in the MagicMirror directory. It looks to me that lines 127 and 130 have a redirect instead of a test. That is,
this: ```>0 ```
should be: ```-gt 0```

**Comment by sdetweil** [comment]
thank you.  fixed

**Comment by sdetweil** [comment]
also was in the raspberry.sh installer, where I extracted the fixuppm2 from...

been looking for this for a couple years now!
JavaScript contaminated!!

**Comment by OldSunGuy** [comment]
Yeah, mixing different languages is a problem when you know more than a few. 

Thanks for the quick fix.
