### ISSUE TITLE
Latest MM commit not updating with script

### ISSUE THREAD

**Issue by kevmang** [sdetweil/MagicMirror_scripts#62]
Hi Sam

Great script! I used to spend at least 15 minutes everytime I updated MM manually going through log files and fiing errors. After finding  your MagicMirror_scripts I haven't had to do this since :)

I've found one minor issue today. MM is saying there's an update as the current installation is 1 commit behind the master branch. when I checked, it's still the same version (2.22.0) but it looks like some documentation was updated without updating the version #.  It looks like your script (and rightfully so) works off version numbers, hence why I get this message in the log file when running your script: local version 2.22.0 already same as master 2.22.0.

Is there any way to force update?

Cheers

**Comment by sdetweil** [comment]
yes, replace apply Parm with force

**Comment by sdetweil** [comment]
this problem is because they didn't update the version, and it's only a readme change.. no code

**Comment by kevmang** [comment]
Force update works perfectly. Thanks!
