### ISSUE TITLE
Jetson Nano clean up

### ISSUE THREAD

**Issue by sharmstr** [sdetweil/MagicMirror_scripts#63]
First off, thank you for the install script.  Worked great on my Jetson Nano.  However, it completely bogged it down.  I know you run a Jetson Nano and not sure if you had a similar issue.

In order to fix it, I removed a bunch of unnecessary stuff that's included with the Jetson image.  It made a world of difference.   I thought you might want to mention this in the readme.

I used the following code, with the exception of NOT removing chromium:  https://gist.github.com/adujardin/c0ee25cfb343ea5b6d17ea88ec6634ac

Anyhow, thank you again for all your hard with on MM.  :)

**Comment by sdetweil** [comment]
thx. my nano is a first version and I didn't experience any slowdowns.  

I will add the link to the readme.

**Comment by sharmstr** [comment]
Mine is too.  But I do have an updated img on it.   Thx
