### ISSUE TITLE
Weather dont loading

### ISSUE THREAD

**Issue by stogli** [sdetweil/MagicMirror_scripts#64]
The weather data is not displayed and it stops when loading!
This problem has existed since the January update, which I only installed now!
Even reinstalling didn't help!
Alternative weather modules show the same problem.
Definitely need help on this matter.

**Comment by sdetweil** [comment]
my scripts have nothing to do with how the modules work on MM. 

the weather module  has a new parameter for openWeather provider, apiVersion , which defaults to 2.5   

what provider are you using.. 

we should take this to the forum 
https://forum.magicmirror.builders/

**Comment by sdetweil** [comment]
i am going to close this now
