### ISSUE TITLE
check pm2 for upgrade during mm upgrade

### ISSUE THREAD

**Issue by sdetweil** [sdetweil/MagicMirror_scripts#66]
mm upgrade fails to run if pm2 downlevel (nodejs change)

**Comment by TomOMaley** [comment]
Hi, no idea whether this is the right Issue to post my problem. I made a new installation both Raspbian and MagicMirror. The latter with your script. Unfortunately I cannot start and stop MM via the commands "pm2 stop mm", "pm2 start mm". I tried to install pm2 manually again but no success.

**Comment by sdetweil** [comment]
if you used my script, the name is not mm

pm2 status

will show you the manged apps

can u post the ~/install.log

**Comment by sdetweil** [comment]
added
