### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by icecreamsanta14** [sdetweil/MagicMirror_scripts#67]
Installing helper tools ...
Updating packages ...
[   <=>                                                                        ]
node: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
bash: line 194: [: -lt: unary operator expected
node: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
Cloning MagicMirror ...
Cloning into 'MagicMirror'...
remote: Enumerating objects: 359, done.
remote: Counting objects: 100% (359/359), done.
remote: Compressing objects: 100% (295/295), done.
remote: Total 359 (delta 64), reused 144 (delta 49), pack-reused 0
Receiving objects: 100% (359/359), 484.52 KiB | 108.00 KiB/s, done.
Resolving deltas: 100% (64/64), done.
Cloning MagicMirror Done!
Installing dependencies ...
bash: line 418: [: -ge: unary operator expected
node: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
Unable to install dependencies!

**Comment by icecreamsanta14** [comment]
fix it

**Comment by sdetweil** [comment]
what did you do to resolve this?

**Comment by sdetweil** [comment]
I added a check for the result of this error 
>node: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
and abort install
