### ISSUE TITLE
Can browser change after installation?

### ISSUE THREAD

**Issue by uok825** [sdetweil/MagicMirror_scripts#68]
Hi, ive been using mm with zerow for like 2 years and today i realized my zero is struggling when try to open mm(chromium). Can i change it now or i need to fresh install. I dont want to lose my config and modified modules. Thx

**Comment by sdetweil** [comment]
you could install the Midori browser and add the environment variable to use it instead of chromium

**Comment by sdetweil** [comment]
can I close this?
