### ISSUE TITLE
MagicMirror_scripts Error

### ISSUE THREAD

**Issue by volkpa99** [sdetweil/MagicMirror_scripts#7]
Hi,
I can't install magicmirror via your script.
I get the error message by following command:
bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"
Error: bash: 404:: Kommando nicht gefunden.

After that I test this command and get another error:
bash -c "$(curl -sL https://github.com/sdetweil/MagicMirror_scripts/blob/master/raspberry.sh)"
Error: bash: /bin/bash: Die Argumentliste ist zu lang

Do you know, whats wrong?

I use a new Raspian Buster setup on my raspberry pi.

Can you help me?

Greetings,
Patrick

**Comment by sdetweil** [comment]
That is that old link. Please cut/paste the link from here

**Comment by volkpa99** [comment]
ok that's clear. But what does the error message on the second command mean? What am I doing wrong?

**Comment by sdetweil** [comment]
Did u cut/paste or type it yourself?

**Comment by sdetweil** [comment]
I used it the other day w cut/paste

**Comment by volkpa99** [comment]
i cut/paste and shows the following error message

**Comment by sdetweil** [comment]
hm.. i just used it, cut/paste from the web page
[](https://www.dropbox.com/s/mdc7qbovq3fn016/Screenshot%20at%202020-05-13%2012-53-48.png?dl=1)

**Comment by sdetweil** [comment]
you used the wrong link for my repo, this is the correct link
bash -c "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/raspberry.sh)"

which is the ;ink shown on the readme page of THIS repo, NOT of MagicMirror

**Comment by volkpa99** [comment]
ok thanks.
I can test it later, but it looks good.

**Comment by sdetweil** [comment]
@volkpa99  have u had a chance to try to correct linked script?

**Comment by sdetweil** [comment]
closing
