### ISSUE TITLE
(node:3424) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 1

### ISSUE THREAD

**Issue by gonzonia** [sdetweil/MagicMirror_scripts#70]
Performing a new install of MM. 

Imaged Rasperry Pi OS (64 bit). 
Ran `sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y`  a couple of times until there were no more updates

Ran `bash -c  "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/raspberry.sh)"`

After seeing "Installing dependencies" I see. 
"(node:3424) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit" multiple times. 

May be nothing but wanted to make sure you were aware.

**Comment by sdetweil** [comment]
yes, we've seen that. but haven't figured out how to stop it.. its not coming from any of our/my code..  

only happens on 64 bit systems
