### ISSUE TITLE
node failed to install, exiting

### ISSUE THREAD

**Issue by sbonaime** [sdetweil/MagicMirror_scripts#75]
Performing a new install of MM with a Rasperry Pi OS (64 bit). arm64
Linux pihome 6.1.58-v8+ #1690 SMP PREEMPT Tue Oct 17 15:37:08 BST 2023 aarch64 GNU/Linux
I updated all packages before the MM installation

end of install.log
````
Installing helper tools ...
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.88.1-10+deb12u4).
wget is already the newest version (1.21.3-1+b1).
git is already the newest version (1:2.39.2-1.1).
build-essential is already the newest version (12.9).
unzip is already the newest version (6.0-28).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
installing on bookworm
installing correct version of node and npm, please wait
  installing : node-v20.8.0
       mkdir : /usr/local/n/versions/node/20.8.0
       fetch : https://nodejs.org/dist/v20.8.0/node-v20.8.0-linux-arm64.tar.xz
node failed to install, exiting
````
I try multiple times with the same results
any idea ? 
Thanks

**Comment by sdetweil** [comment]
looks like there is a network problem trying to download the file.  it works ok here  pi, desktop and phone.

can u click on this link in your post 
https://nodejs.org/dist/v20.8.0/node-v20.8.0-linux-arm64.tar.xz

**Comment by sbonaime** [comment]
I was using  zsh. After switching to bash, the installation was a success !
