### ISSUE TITLE
ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory 

### ISSUE THREAD

**Issue by ChrisRG711** [sdetweil/MagicMirror_scripts#76]
Brand new PI OS 64 bit. Ran the installation script from here. 
Then downloaded the error file  MagicMirror-error.log

I saw a thread similar to this in magic mirror forum. but didn't see a solution i could follow. What did i do wrong?

**Comment by ChrisRG711** [comment]
that didnt really help i still get the same message and sometimes a bit more
[2655:1023/162650.271154:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
/home/crg/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT

here is the mm.sh 
cd /home/crg/MagicMirror
export ELECTRON_DISABLE_GPU=1
DISPLAY=:0 npm start

**Comment by sdetweil** [comment]
hm.. should have fixed it.. did on earlier electron versions
https://github.com/electron/forge/issues/3266

nothing we can do
