### ISSUE TITLE
Script Stuck at dependencies installation 

### ISSUE THREAD

**Issue by jjatin31** [sdetweil/MagicMirror_scripts#8]
After running the script installation command:
bash -c "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/raspberry.sh)"

execution stuck at dependencies installation 
/home/pi/MagicMirror
I waited here for a long time but script stuck here 

Installing dependencies ...
npm WARN deprecated time-grunt@2.0.0: Deprecated because Grunt is practically unmaintained. Move on to something better. This package will continue to work with Grunt v1, but it will not receive any updates.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated rrule-alt@2.2.8: Please use rrule instead
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated webdriverio@4.14.4: outdated version, please use @next
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm 

Kindly assist..

**Comment by sdetweil** [comment]
what did you do?  did it get past there?

**Comment by jjatin31** [comment]
Hi Sam,

That issue was resolved now there is one more.

PFB the Snip:

[image: image.png]

Kindly assist.

Regards,
Jatin

**Comment by sdetweil** [comment]
sorry, the image doesn't show..

**Comment by jjatin31** [comment]
Hi sam,

Installation is completed successfully.but when try to start npm i got this
following error.

*We're ready! Run DISPLAY=:0 npm start from the ~/MagicMirror directory to
start your MagicMirror.*

* pi@raspberry:~ $ DISPLAY=:0 npm start*
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/pi/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open
'/home/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-05-14T19_24_16_614Z-debug.log

Regards,
Jatin

**Comment by sdetweil** [comment]
'/home/pi/package.json'

you are in the home folder, must be in the MagicMirror folder

**Comment by jjatin31** [comment]
Hi Sam,

Thank you soo much it working fine and great project and work.

I'm working in IT Support. This is my first time on linux.

Due to Covid-19. I'm just trying new things at home.

Kindly suggest some projects like this MagicMirror.

Again thank you for your help..

Regards,
Jatin
