### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by mrfoxie** [sdetweil/MagicMirror_scripts#87]
After adding modules its not starting up but it shows that it is online

```bash
pm2 status
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ MagicMirror        │ fork     │ 55   │ online    │ 0%       │ 3.0mb    │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
```

**Comment by sdetweil** [comment]
do

pm2 stop all
pm2 logs --lines=100

**Comment by mauriziov** [comment]
I have  a similar issue, MagicMirror is not starting but after an update. Below the log:

 0|MagicMir | > DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js
0|MagicMir |
0|MagicMir |
0|MagicMir | > magicmirror@2.27.0 start
0|MagicMir | > DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js
0|MagicMir |
0|MagicMir |
0|MagicMir | > magicmirror@2.27.0 start
0|MagicMir | > DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js
0|MagicMir |

/home/dietpi/.pm2/logs/MagicMirror-error.log last 100 lines:
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found
0|MagicMir | sh: 1: ./node_modules/.bin/electron: not found

**Comment by chintito4ever** [comment]
I have experienced issues every time I updated, so sick of this. Not going to use this script ever.

**Comment by sdetweil** [comment]
if you dont post the upgrade log i cant help much.

the upgrade log is ~/MagicMirror/installers/upgrade.log

i have been out of town for a while, just getting back, 

this is an npm install problem.  they dont test on diet pi.

**Comment by BauzyMM** [comment]
Hi, 
Have the same issue. When upgrading MM there is a error message in news feed when MM is started. When commented out the MM can be started from cammand prompt, but automatic start will crash after about 20 sec.

Log from installation attached. What's the issue? :)
[_MagicMirror_installers_upgrade_logfile.txt](https://github.com/sdetweil/MagicMirror_scripts/files/14896051/_MagicMirror_installers_upgrade_logfile.txt)

**Comment by sdetweil** [comment]
thanks for the log. it doesnt show any issue on the actual upgrade.

can you use manusl start to capture tge error?

pm2 stop all
cd ~/MagicMirror
npm start >somefile.txt 2>&1
wait til the error and then try ctrl-q top stop mm
then edit the somefile.txt. and go to the bottom

if you want to post that file here, please check and edit out any calendar urls, as these are used in logging the number of events processed. helps when you have multiple calendars being processed

**Comment by BauzyMM** [comment]
Thanks, attached is the log file. Had no issues before the upgrade. 
[MM2 log.txt](https://github.com/sdetweil/MagicMirror_scripts/files/14898510/MM2.log.txt)

Also attaching the same log file but with news feed back in the config.js.
[log MM with newsfeed active in config.txt](https://github.com/sdetweil/MagicMirror_scripts/files/14898617/log.MM.with.newsfeed.active.in.config.txt)

Looks like somthing with permissions, but as written, worked before and internet connection is fine.

**Comment by sdetweil** [comment]
things change when there are changes.. pm2 is not our code, so you never know..

issue the command to fix it.. 
```text
[2024-04-07 21:06:36.565] [ERROR] [PM2][ERROR] Permission denied, to give access to current user:
 sudo chown pi:pi /home/pi/.pm2/rpc.sock /home/pi/.pm2/pub.sock
```

on the newsfeed, there was a network timeout.. sadly most of the modules do not handle errors very well..

**Comment by BauzyMM** [comment]
Saw that in the log and tried the command before, MM still crashes after about 5-10 seconds after starting up and feching data.

Any more ideas?

**Comment by sdetweil** [comment]
and if you do

ls -laF /home/pi/.pm2/rpc.sock

do you see current use as the owner?
note the command says pi, but that might not be the username

**Comment by BauzyMM** [comment]
If I do:
pi@raspberrypi:~ $ sudo chown pi:pi /home/pi/.pm2/rpc.sock /home/pi/.pm2/pub.sock
pi@raspberrypi:~ $ ls -laF /home/pi/.pm2/rpc.sock                               srwxrwxr-x 1 pi pi 0 10 apr 07.04 /home/pi/.pm2/rpc.sock=

The MM starts up fine if I start it from command prompt. When doing a reboot and doing the command, the user has changed back to root.

Comandprompt after reboot:
pi@raspberrypi:~ $ ls -laF /home/pi/.pm2/rpc.sock
srwxrwxr-x 1 root root 0 10 apr 07.04 /home/pi/.pm2/rpc.sock=
pi@raspberrypi:~ $ sudo chown pi:pi /home/pi/.pm2/rpc.sock /home/pi/.pm2/pub.sock
pi@raspberrypi:~ $ ls -laF /home/pi/.pm2/rpc.sock                               srwxrwxr-x 1 pi pi 0 10 apr 07.04 /home/pi/.pm2/rpc.sock=
 
user changes back to root at reboot, why?

**Comment by sdetweil** [comment]
were you logged on as root when you did the mm scripts?  or did you try some of this before running my script? 

run the fixuppm2 script logged on as user

**Comment by luci-11** [comment]
hello,
same problem here. the script results online but nothing else happened.
I also noticed that probably the external_browser configuration is not working anymore, could it be? At reboot I always get a chromium error .Maybe this can help in troubleshooting too.  Thanks in advance

**Comment by luci-11** [comment]
So..
I started again with a clean installation as this is what i was trying to do. I selected yes to disable splashscreen and to pm2 to autostart.
This is the output: 
[pm2_50.txt](https://github.com/sdetweil/MagicMirror_scripts/files/14996793/pm2_50.txt)

and install.log attached
[install.log](https://github.com/sdetweil/MagicMirror_scripts/files/14996809/install.log)

If i need to launch anything with the external_browser modification or  an updgrade too let me know.

**Comment by sdetweil** [comment]
yes if it's a new os install they have removed chrome on armv6l.

so you would have to use Firefox or another browser. that has to be installed manually 

but, if we worked before mm update,  how did we get into this os updated state?

**Comment by luci-11** [comment]
In my case,it is a fresh install of everything, both rasp os and MM through your script.
It's the latest version of raspberry os available online and firefox was removed too. 

Now I've installed midori (tested working with desktop) and changed the mm.sh then reboot. 
Still get the splashscreen, but then desktop appears and log is full of:
0|MagicMirror  | > magicmirror@2.27.0 start
0|MagicMirror  | > ./run-start.sh $1
PM2            | App [MagicMirror:0] exited with code [0] via signal [SIGINT]
PM2            | App [MagicMirror:0] starting in -fork mode-
PM2            | App [MagicMirror:0] online

**Comment by sdetweil** [comment]
ok, for pi0w you need to run the legacy 32 bit image, right?

**Comment by luci-11** [comment]
ok I feel like an idiot ..   anyway...
i reinstalled with 32 bit-  MM worked.
I tested the reboot and MM was not working anymore (online but no signs of midori).
I checked this ---->    ls -laF /home/pi/.pm2/rpc.sock  for me the output was ok.
I tried starting again MM using the run-start.sh  and found out it is not reading external_browser anymore from the installer/mm.sh file..
If I set the variable in terminal it works.
Now i've put it in ~/.profile , not sure if it is the best way to handle this,  the env variable is kept so i can launch run-start.sh manually.
But autostart at reboot still doesn't work....

**Comment by luci-11** [comment]
```
/home/pi/.pm2/logs/MagicMirror-error.log last 15 lines:
0|MagicMir | Require stack:
0|MagicMir | - /home/pi/MagicMirror/js/electron.js
0|MagicMir |     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
0|MagicMir |     at Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:81:25)
0|MagicMir |     at require (node:internal/modules/helpers:130:18)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/js/electron.js:3:18)
0|MagicMir |     at Module._compile (node:internal/modules/cjs/loader:1241:14)
0|MagicMir |     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
0|MagicMir |     at Module.load (node:internal/modules/cjs/loader:1091:32)
0|MagicMir |     at Module._load (node:internal/modules/cjs/loader:938:12)
0|MagicMir |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|MagicMir |     at Module._compile (node:internal/modules/cjs/loader:1241:14) {
0|MagicMir |   code: 'MODULE_NOT_FOUND',
0|MagicMir |   requireStack: [ '/home/pi/MagicMirror/js/electron.js' ]
```

**Comment by sdetweil** [comment]
does the external have the export in front of it??

export EXTERNAL_BROWSER=

in linux environment variables are NOT passed to children processes by default, so you MUST use export
in Windows  environment variaables ARE passed

**Comment by luci-11** [comment]
> @luci-11
> 
> /pm2/node_modules/require-in-the-middle
> 
> so this is a pm2 problem...
> 
> run the fixuppm2 script from my scripts page...
> 
> I have not seen this error before.. unless we switched node versions out from under pm2..
> 
> try this sudo npm i pm2 -g
> 
> then restart using pm2

I tried but still online and no MM running :( about variables, yes I used the export as written in the guide. But at least i have a solution.
Just for better understanding,. is pm2 really necessary? I mean, is it completely wrong if we just make the run-start.sh executable at boot as "workaround".  Thanks a lot for your help

**Comment by sdetweil** [comment]
the users problem you linked to as a missing library the module didn't declare.. my upgrade script would have fixed that 

export ELECTRON_DISABLE_GPU=1  only applies if you are using the built in electron browser which is no longer available for armv6l systems

**Comment by luci-11** [comment]
Hi, back again.
I just wanted to update you about what I did to make everything up and running after reboot :) ..
Maybe will help for troubleshooting  or others:
- put complete path for mm.sh and config in installers/pm2_MagicMirror_new.json (but I don't think this affected the result)
- manually reinstalled npm2 just typing with` sudo npm install -g pm2`
- setup the mm.sh script outside MagicMirror directory so inside` /home/pi ` and setup pm2 following this [mm documentation](https://docs.magicmirror.builders/configuration/autostart.html#using-pm2)

**Comment by sdetweil** [comment]
@luci-11 hmm.. weird

1. complete path in json file.. I do that already
2. this was the problem I think.  but I don't know why, as the script JUST did this. 
3. ok.. as I said, weird..  i've had 100s maybe 1000s of installs without this difficulty.

**Comment by slecram** [comment]
Hi guys, is there a solution for this issue yet?

**Comment by sdetweil** [comment]
@slecram  in general this is a case by case problem..

I see it more on pi4/5 with Wayland instead of x11.

it's more a pm2 problem than MagicMirror 

try reinstalling pm2
sudo npm install -g pm2

**Comment by slecram** [comment]
I get the issue on pi zero 2 with raspberry pi os 32-bit.
I just reinstalled pm2 by "sudo npm install -g pm2" with no change. There i got warnings:

```
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

![image](https://github.com/sdetweil/MagicMirror_scripts/assets/62532513/cee8ef9b-3af4-4534-b5f7-acb4d614f141)


![image](https://github.com/sdetweil/MagicMirror_scripts/assets/62532513/480f7332-3537-4ce2-a701-5e782bf28f44)


![image](https://github.com/sdetweil/MagicMirror_scripts/assets/62532513/e8fbd2c7-ec80-43d2-96e0-de379b2fd17e)







Errorlogs with missed electron module

**Comment by sdetweil** [comment]
ah, pi2

can you show results of
uname -a
and
grep start package.json

and attach the log
~/install.log

this is the legacy image, right?
for armv6l

there is no electron anymore for armv6l
on the bookworm image they have also removed chromium, so you have to install Firefox or minority and add a parm to the mm.sh to tell my special startup script what browser to use

**Comment by slecram** [comment]
Good morning, are there some news?

**Comment by sdetweil** [comment]
sorry, i didn't see your post from before 

the logs says you aborted the install , and attempted to install again.. 
```text 
Note: the node command changed location and the old location may be remembered in your current shell.
         old : /usr/bin/node
         new : /usr/local/bin/node
If "node --version" shows the old version then start a new shell, or reset the location hash with:
hash -r  (for bash, zsh, ash, dash, and ksh)
rehash   (for csh and tcsh)
[96mCloning MagicMirror ...[0m
[92mCloning MagicMirror Done![0m
[96mInstalling dependencies ...[0m    <-------  --- last MM install output
install starting  - Thu May 23 11:34:12 CEST 2024   <<< install restarted
installing on armv7l processor system
```
and then the log says
```
installing on bookworm
[93mIt seems like MagicMirror is already installed.
To prevent overwriting, the installer will be aborted. 
Please rename the [1m~/MagicMirror[0m[93m folder and try again.[0m
```

SO, I won't install OVER a prior installation of  MagicMirror.. 

if you want to do this, then u have to move the existing MagicMirror folder out of the way (or delete it)

**Comment by slecram** [comment]
Thank you!! That was the problem. I delete /Magic Mirror/ and reinstall it. Now it runs without problems!
I don't know why the installation aborted ago

**Comment by sdetweil** [comment]
it SHOULD have output this to the screen , on the second install attempt
```text
�[93mIt seems like MagicMirror is already installed.
To prevent overwriting, the installer will be aborted. 
Please rename the �[1m~/MagicMirror�[0m�[93m folder and try again.�[0m
```
