### ISSUE TITLE
Error in MM Install Script

### ISSUE THREAD

**Issue by htilburgs** [sdetweil/MagicMirror_scripts#88]
During installation, the next error appears

> Installing dependencies ...
(node:27185) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit

**Comment by sdetweil** [comment]
that is the npm code with an error message, nothing we can do.

it's  ot fatal   so just ignore it
