### ISSUE TITLE
Install Script: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by ajkurtz** [sdetweil/MagicMirror_scripts#89]
I tried running the install script on a raspberry pi (specifically a Raspberry Pi 3 Model B Plus Rev 1.3) and the script crashes with this error:

`Cloning MagicMirror Done!
Installing dependencies ...
[..................] \ idealTree:MagicMirror: sill idealTree buildDeps
<--- Last few GCs --->

[8510:0x614cb28]    40075 ms: Scavenge (reduce) 225.3 (233.1) -> 225.3 (233.3) MB, 3.07 / 0.00 ms  (average mu = 0.987, current mu = 0.994) allocation failure; 
[8510:0x614cb28]    40108 ms: Mark-Compact (reduce) 225.6 (233.3) -> 225.4 (233.8) MB, 30.19 / 0.29 ms  (+ 70.6 ms in 243 steps since start of marking, biggest step 31.1 ms, walltime since start of marking 505 ms) (average mu = 0.963, current mu = 0.877) 

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

Unable to install dependencies! `

Here is the contents of the install.log, but the error I got on the terminal is not in there.  
[install.log](https://github.com/user-attachments/files/15750434/install.log)

Andy

**Comment by sdetweil** [comment]
can you show me the output of free -m

**Comment by ajkurtz** [comment]
Sorry, I was out of town for a few days.

![image](https://github.com/sdetweil/MagicMirror_scripts/assets/10631332/c7bf846d-5c3d-438c-b5a2-d1e2ab36db92)

**Comment by sdetweil** [comment]
hm.. not out of memory, didn't use swap..  will review.. options

**Comment by sdetweil** [comment]
ok, if you stiull want to try 

try this

in the terminal window before pasting the command do 
```sh
rm -rf ~/MagicMirror
export NODE_OPTIONS=--max_old_space_size=4096
```

then copy/paste the install script line

le me know

**Comment by rholak** [comment]
I also tried this on a 1GB Pi and received the same error. Setting that flag to 4096 causes node to crash immediately with the heap error. After some testing, I got npm to install all the packages successfully with max_old_space_size set to 800.
Hopefully, this helps @ajkurtz  as well.

**Comment by sdetweil** [comment]
thank you for the feedback..  
I am surprised, asn the system should use swap space
