### ISSUE TITLE
raspberrypi 4 download failed

### ISSUE THREAD

**Issue by jpk0305** [sdetweil/MagicMirror_scripts#92]
line 86,88,90,91,168 permission denied
install.log permission denied

**Comment by sdetweil** [comment]
try  again..

**Comment by jpk0305** [comment]
install log being saved to /home/pi/install.log
Updating packages ...
W: http://raspbian.raspberrypi.com/raspbian/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: Release file for http://raspbian.raspberrypi.com/raspbian/dists/bookworm/InRelease is not valid yet (invalid for another 108d 6h 21min 39s). Updates for this repository will not be applied.
E: Release file for http://archive.raspberrypi.com/debian/dists/bookworm/InRelease is not valid yet (invalid for another 104d 16h 23min 7s). Updates for this repository will not be applied.
Update failed, retrying installation ...
Installing helper tools ...
E: 의존성이 맞지 않습니다. 패키지 없이 'apt --fix-broken install'을 시도해 보십시오 (아니면 해결 방법을 지정하십시오).
E: Release file for http://archive.raspberrypi.com/debian/dists/bookworm/InRelease is not valid yet (invalid for another 104일 16시간 22분 58초). Updates for this repository will not be applied.
W: http://raspbian.raspberrypi.com/raspbian/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: Release file for http://raspbian.raspberrypi.com/raspbian/dists/bookworm/InRelease is not valid yet (invalid for another 108일 6시간 21분 29초). Updates for this repository will not be applied.
bash: 줄 444: npm: 명령어를 찾을 수 없음
Cloning MagicMirror ...
'MagicMirror'에 복제합니다...
remote: Enumerating objects: 399, done.
remote: Counting objects: 100% (399/399), done.
remote: Compressing objects: 100% (313/313), done.
remote: Total 399 (delta 82), reused 194 (delta 71), pack-reused 0
오브젝트를 받는 중: 100% (399/399), 476.95 KiB | 2.68 MiB/s, 완료.
델타를 알아내는 중: 100% (82/82), 완료.
Cloning MagicMirror Done!
Installing dependencies ...
bash: 행 519번: [: -ge: 단항 연산자가 필요합니다
bash: 줄 523: npm: 명령어를 찾을 수 없음
Unable to install dependencies!

**Comment by jpk0305** [comment]
help me please..

**Comment by sdetweil** [comment]
sounds like the system Date is incorrect

108 days prior to bookworm release.

**Comment by sdetweil** [comment]
i'm going to close this.. reopen if you need more help
