### ISSUE TITLE
Install hangs on "Installing helper tools..."

### ISSUE THREAD

**Issue by HaViGit** [sdetweil/MagicMirror_scripts#93]
Short after running the script on my RPi3b Compute Module the script freezes with the line "Installing helper tools ...". Do you perhaps have a solution for me?

**Comment by sdetweil** [comment]
can you show me the ~/install.log

**Comment by HaViGit** [comment]
Thanks for quick responding. After I posted the message I tried a manual installation of MM and the system also hangs, now with the message "Installing vendor files...". Here is the log file, I hope you can do something with it.

``install starting  - Wed Jul 10 14:44:36 CEST 2024
installing on aarch64 processor system
the os is Distributor ID: Debian Description: Debian GNU/Linux 12 (bookworm) Release: 12 Codename: bookworm
               total        used        free      shared  buff/cache   available
Mem:             417         163         118           0         193         253
Swap:            199         194           5
^[[96mUpdating packages ...^[[0m
Hit:1 http://deb.debian.org/debian bookworm InRelease Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease Hit:3 http://deb.debian.org/debian bookworm-updates InRelease Hit:4 http://archive.raspberrypi.com/debian bookworm InRelease Reading package lists...
apt-get update  completed ok
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  doc-base
The following NEW packages will be installed:
  pv
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 58.6 kB of archives.
After this operation, 146 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main arm64 pv arm64 1.6.20-1 [58.6 kB]
Fetched 58.6 kB in 0s (724 kB/s)
Selecting previously unselected package pv.
(Reading database ... ^M(Reading database ... 5%^M(Reading database ... 10%^M(Reading database ... 15%^M(Reading database ... 20%^M(Reading database ... 25%^M(Reading database ... 30%^M(Reading database ... 35%^M(Reading database ... 40%^M(Reading database ... 45%^M(Reading database ... 50%^M(Readin>Preparing to unpack .../archives/pv_1.6.20-1_arm64.deb ...
Unpacking pv (1.6.20-1) ...
Setting up pv (1.6.20-1) ...
Processing triggers for man-db (2.11.2-2) ...
apt-get upgrade  started
apt-get upgrade result =rc=0 Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
^[[96mInstalling helper tools ...^[[0m
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.88.1-10+deb12u6).
wget is already the newest version (1.21.3-1+b1).
wget set to manually installed.
git is already the newest version (1:2.39.2-1.1).
build-essential is already the newest version (12.9).
unzip is already the newest version (6.0-28).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 this should be a raspberry pi 02w
increasing swap space
``

**Comment by HaViGit** [comment]
After a second attempt (and cleaning the installations log) the system now hangs with the message "installing dependencies". The log file can be found below.

``  GNU nano 7.2                                           install.log                                                    install starting  - Wed Jul 10 16:27:17 CEST 2024
installing on aarch64 processor system
the os is Distributor ID: Debian Description: Debian GNU/Linux 12 (bookworm) Release: 12 Codename: bookworm
               total        used        free      shared  buff/cache   available
Mem:             417         227          97           0         143         189
Swap:            199         142          57
^[[96mUpdating packages ...^[[0m
Hit:1 http://deb.debian.org/debian bookworm InRelease Hit:2 http://deb.debian.org/debian-security bookworm-security InR>apt-get update  completed ok
Reading package lists...
Building dependency tree...
Reading state information...
pv is already the newest version (1.6.20-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
apt-get upgrade  started
apt-get upgrade result =rc=0 Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
^[[96mInstalling helper tools ...^[[0m
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.88.1-10+deb12u6).
wget is already the newest version (1.21.3-1+b1).
git is already the newest version (1:2.39.2-1.1).
build-essential is already the newest version (12.9).
unzip is already the newest version (6.0-28).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 this should be a raspberry pi 02w
increasing swap space
want /var/swap=200MByte, checking existing: keeping it
installing on bookworm
^[[96mCloning MagicMirror ...^[[0m
^[[92mCloning MagicMirror Done!^[[0m
^[[96mInstalling dependencies ...^[[0m``

**Comment by meshe-dev** [comment]
I'm doing an install from scratch today and I ran into this error as well. It's freezing on the setup command for resizing the swap space.

I'm using a Pi 3 and had installed the 64bit version of Raspbian, switching back to 32bit fixed the issues.

**Comment by HaViGit** [comment]
Thanks!

**Comment by sdetweil** [comment]
i think i fixed this
