### ISSUE TITLE
how to Stop or Pause mirror?

### ISSUE THREAD

**Issue by tung256** [sdetweil/MagicMirror_scripts#94]
your raspberry.sh works great!
now, how to Stop or Pause so i can go back to the desktop GUI?
if i do ALT+F4   or CTRL+W  it closes MM but MM auto resumes within 1 seconds on the rpi4 (bookworm).

please help. thanks!

**Comment by sdetweil** [comment]
ctrl-m

minimizes MagicMirror

**Comment by tung256** [comment]
@sdetweil   works great. thanks!
