### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by ibrahim5albakri** [sdetweil/MagicMirror_scripts#95]
npm install
npm error code 1
npm error path /home/pi/MagicMirror/node_modules/electron
npm error command failed
npm error command sh -c node install.js
npm error RequestError
npm error     at ClientRequest.<anonymous> (/home/pi/MagicMirror/node_modules/got/source/request-as-event-emitter.js:178:14)
npm error     at Object.onceWrapper (node:events:634:26)
npm error     at ClientRequest.emit (node:events:531:35)
npm error     at origin.emit (/home/pi/MagicMirror/node_modules/@szmarczak/http-timer/source/index.js:37:11)
npm error     at emitErrorEvent (node:_http_client:103:11)
npm error     at TLSSocket.socketErrorListener (node:_http_client:506:5)
npm error     at TLSSocket.emit (node:events:519:28)
npm error     at emitErrorNT (node:internal/streams/destroy:170:8)
npm error     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
npm error     at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
npm error A complete log of this run can be found in: /home/pi/.npm/_logs/2024-09-22T14_52_33_462Z-debug-0.log

**Comment by sdetweil** [comment]
can you post the ~/install.log please

**Comment by ibrahim5albakri** [comment]
> can you post the ~/install.log please

how

**Comment by ibrahim5albakri** [comment]
> can you post the ~/install.log please

install starting  - Sun Sep 22 18:06:07 +03 2024
installing on aarch64 processor system
the os is PRETTY_NAME="Debian GNU/Linux 12 (bookworm)" NAME="Debian GNU/Linux" VERSION_ID="12" VERSION="12 (bookworm)" VERSION_CODENAME=bookworm ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"
               total        used        free      shared  buff/cache   available
Mem:            7809         865        5569          79        1576        6944
Swap:            199           0         199
[96mUpdating packages ...[0m

[91mUpdate failed, retrying installation ...[0m
[96mInstalling helper tools ...[0m
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
installing on bookworm
[93mIt seems like MagicMirror is already installed.
To prevent overwriting, the installer will be aborted.
Please rename the [1m~/MagicMirror[0m[93m folder and try again.[0m

**Comment by sdetweil** [comment]
ok, looks like you tried your best install MagicMirror already. my script will not install over, only new

what user id are you using ? not root or sudo, right?
looks like the apt update failed, if the user doesn't have sudo rights, then you will be prompted for the root user password like normal.

the execution in first logs is /MagicMirror/node_modules/electron, but that is not the correct path, so it sounds like package.json was edited too for some reason.

**Comment by ibrahim5albakri** [comment]
> ok, looks like you tried your best install MagicMirror already. my script will not install over, only new
> 
> what user id are you using ? not root or sudo, right? looks like the apt update failed, if the user doesn't have sudo rights, then you will be prompted for the root user password like normal.
> 
> the execution in first logs is /MagicMirror/node_modules/electron, but that is not the correct path, so it sounds like package.json was edited too for some reason.

yes i try
how can fix it

**Comment by sdetweil** [comment]
remove or rename the MagicMirror folder
but you need to insure the apt update works too

**Comment by ibrahim5albakri** [comment]
> remove or rename the MagicMirror folder but you need to insure the apt update works too

install log being saved to /home/pi/install.log
Updating packages ...
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
Update failed, retrying installation ...
Installing helper tools ...
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
Cloning MagicMirror ...
Cloning into 'MagicMirror'...
remote: Enumerating objects: 399, done.
remote: Counting objects: 100% (399/399), done.
remote: Compressing objects: 100% (312/312), done.
remote: Total 399 (delta 79), reused 187 (delta 72), pack-reused 0 (from 0)
Receiving objects: 100% (399/399), 456.90 KiB | 12.00 KiB/s, done.
Resolving deltas: 100% (79/79), done.
Cloning MagicMirror Done!
Installing dependencies ...
npm error code ECONNRESET
npm error network aborted
npm error network This is a problem related to network connectivity.
npm error network In most cases you are behind a proxy or have bad network settings.
npm error network
npm error network If you are behind a proxy, please make sure that the
npm error network 'proxy' config is set properly.  See: 'npm help config'
npm error A complete log of this run can be found in: /home/pi/.npm/_logs/2024-09-22T15_59_06_628Z-debug-0.log
npm error code 1
npm error path /home/pi/MagicMirror
npm error command failed
npm error command sh -c npm run install-vendor && npm run install-fonts && echo "MagicMirrorÂ² installation finished successfully! 
npm error command "
npm error A complete log of this run can be found in: /home/pi/.npm/_logs/2024-09-22T15_44_47_520Z-debug-0.log
Unable to install dependencies!

**Comment by sdetweil** [comment]
yes

Updating packages ...
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
Update failed, retrying installation ...


and

Installing dependencies ...
npm error code ECONNRESET
npm error network aborted
npm error network This is a problem related to network connectivity.

i dou not know why either problem, they are system problems outside by script

**Comment by ibrahim5albakri** [comment]
> yes
> 
> Updating packages ... sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set Update failed, retrying installation ...
> 
> and
> 
> Installing dependencies ... npm error code ECONNRESET npm error network aborted npm error network This is a problem related to network connectivity.
> 
> i do not know why either problem, they are system problems outside my script

Can you upload the entire zipped project file for me, and I can directly transfer it to the drawing without downloading or installing any libraries?

**Comment by sdetweil** [comment]
no. too big, and i am only on my phone now

**Comment by ibrahim5albakri** [comment]
> insure the apt update works too

When you have free time and access to a computer, could you please upload the file for me? Thank you in advance.

**Comment by sdetweil** [comment]
no. it depends on os level, and too
many other things, why we build on site

**Comment by ibrahim5albakri** [comment]
> no. it depends on os level, and too many other things, why we build on site

So what is the solution to this problem? It has exhausted me for more than 8 hours. I try and try and fail

**Comment by sdetweil** [comment]
i do not kmow

solve the sudo problem first

where are you in the world?  network appears limited

**Comment by ibrahim5albakri** [comment]
> i do not kmow
> 
> solve the sudo problem first
> 
> where are you in the world?  network appears limited 
I am from Syria, the city of Khalab, but I use VPN in the United States of America

**Comment by ibrahim5albakri** [comment]
> i do not kmow
> 
> solve the sudo problem first
> 
> where are you in the world?  network appears limited 
I am from Syria, the city of Khalab, but I use VPN in the United States of America

**Comment by ibrahim5albakri** [comment]
> i do not kmow
> 
> solve the sudo problem first
> 
> where are you in the world?  network appears limited 

Good morning. I deleted the operating system and tried again, and the installation was successful, but when I run it, nothing appears, as if it freezes![IMG_20240923_113951.jpg](https://github.com/user-attachments/assets/8605d203-3935-4946-90c3-f1a1ce87bde6)

![IMG_20240923_113958.jpg](https://github.com/user-attachments/assets/d8ef8330-2dc7-4083-9e6e-215953a1b360)

**Comment by sdetweil** [comment]
I need to see the output of npm start

**Comment by sdetweil** [comment]
what changed?
