### ISSUE TITLE
update-script.sh hangs after "saving custom.css"

### ISSUE THREAD

**Issue by xIExodusIx** [sdetweil/MagicMirror_scripts#96]
Hi sdetweil,

here can I send you the upgrade.log

[upgrade.log](https://github.com/user-attachments/files/17211457/upgrade.log)
 
I hope this will help.

**Comment by sdetweil** [comment]
crazy. just stops in the middle of nothing. i asked in the forum if your disk space was running out

**Comment by xIExodusIx** [comment]
df -k shows:

Filesystem     1K-blocks    Used Available Use% Mounted on
udev             1667704       0   1667704   0% /dev
tmpfs             388200    1444    386756   1% /run
/dev/sda2       61387080 7699368  50549572  14% /
tmpfs            1940984   34100   1906884   2% /dev/shm
tmpfs               5120      16      5104   1% /run/lock
/dev/sda1         522230   77064    445166  15% /boot/firmware
tmpfs             388196      40    388156   1% /run/user/1000

I think there is ebnough space left.

**Comment by sdetweil** [comment]
thanks.   still pondering next debug steps

**Comment by xIExodusIx** [comment]
MagicMirror is a great project, it's just a shame that so many great modules don't run or only partially run. e.g. MMM-Fuel 
is supposed to show cheap petrol prices, it works, but unfortunately it only shows petrol stations, the addresses and the distance, but not the petrol prices. And there are some Modules more that don't run as expected.

**Comment by xIExodusIx** [comment]
Maybe the problem is with Raspi OS Bookworm?

**Comment by sdetweil** [comment]
others are using bookworm wo trouble

**Comment by xIExodusIx** [comment]
I reinstalled MM today on the Pi4, until yesterday I had MM on a Pi3 B+ Rev 1.3. Also with Bookworm 64bit. On the Pi 3 I had the same problem that the upgrad-script.sh stopped at "saving Custom.css".

**Comment by sdetweil** [comment]
yes, it is writing a message to the log after that saving message.

**Comment by PeterFleur** [comment]
I have the same on Debian Bookworm on a HP Thin Client. Removing custom.css beforehand does not change the situation (except that it hangs without the message saving custom.css)

**Comment by PKIMOS** [comment]
This is key**F**ile
keyFile=package.json

and it is referenced as keyfile
local_version=$(grep -m1 version $keyfile | awk -F\" '{print $4}' | awk -F-  '{print $1}')

changing the define to keyfile, all lowercase fixed it for me.

**Comment by PeterFleur** [comment]
Looks like that's the trick! It goes further for me now

**Comment by sdetweil** [comment]
fixed

should have thrown an error
