### ISSUE TITLE
mm.sh lost on upgrade (2.29) 

### ISSUE THREAD

**Issue by sdetweil** [sdetweil/MagicMirror_scripts#97]
fix upgrade script to save/restore mm.sh

**Comment by Blackbird17k** [comment]
On upgrade to 2.29, I received error:

`(node:1475407) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit`

I removed MagicMirror, reinstalled, received same error.

**Comment by sdetweil** [comment]
yes, this is an npm bug, does not affect the MagicMirror install or update
