### ISSUE TITLE
Potentially npm issue?

### ISSUE THREAD

**Issue by jhartung2** [sdetweil/MagicMirror_scripts#98]
install starting  - Sat Nov  2 15:44:53 CDT 2024
installing on aarch64 processor system
the os is PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)" NAME="Raspbian GNU/Linux" VERSION_ID="11" VERSION="11 (bullseye)" VERSION_CODENAME=bullseye ID=raspbian ID_LIKE=debian HOME_URL="http://www.raspbian.org/" SUPPORT_URL="http://www.raspbian.org/RaspbianForums" BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
               total        used        free      shared  buff/cache   available
Mem:            3794         613        2099         189        1081        2915
Swap:             99           0          99
[96mUpdating packages ...[0m
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease Hit:2 https://deb.nodesource.com/node_23.x nodistro InRelease Hit:3 http://raspbian.raspberrypi.org/raspbian bullseye InRelease Reading package lists...
apt-get update  completed ok
Reading package lists...
Building dependency tree...
Reading state information...
pv is already the newest version (1.6.6-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
apt-get upgrade  started
apt-get upgrade result =rc=0 Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[96mInstalling helper tools ...[0m
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.9).
curl is already the newest version (7.74.0-1.3+deb11u13).
git is already the newest version (1:2.30.2-1+deb11u3).
unzip is already the newest version (6.0-26+deb11u1).
wget is already the newest version (1.21-1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
node not installed, trying via apt-get
Reading package lists... Building dependency tree... Reading state information... E: Unable to locate package nodejs:armv7l E: Unable to locate package npm:armv7l
npm not installed, trying via apt-get
npm installed now, install n
Reading package lists... Building dependency tree... Reading state information... Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming. The following information may help to resolve the situation: The following packages have unmet dependencies: libnode72 : Conflicts: nodejs-legacy nodejs : Conflicts: npm E: Unable to correct problems, you have held broken packages.
sudo: npm: command not found
installing on bullseye
[96mCloning MagicMirror ...[0m
[92mCloning MagicMirror Done![0m
[96mInstalling dependencies ...[0m

[91mUnable to install dependencies! [0m

I was having issues with Nodejs so I deleted it, assuming this script downloaded the latest version, which it appears (?) it does. Any thoughts? I've been struggling with this for a couple days. Appreciate any advice. Thanks in advance.

**Comment by sdetweil** [comment]
i am away from systems til Monday

can you run this
``` 
dpkg --print-architecture | grep armhf
``` 

also try running install again, added a fix for this
you may have to delete the MagicMirror folder too before running install again

**Comment by jhartung2** [comment]
That worked perfectly. Thank you so much. You have no idea how quickly my headache went away! You, sir, are amazing.

**Comment by sdetweil** [comment]
i need to keep this open til i can review why this failed

**Comment by sdetweil** [comment]
can u post tye output of that command string

**Comment by jhartung2** [comment]
Sorry, I was away and will get that output to you once I have access to the Pi again. But I will say that after posting the bug but prior to your response, I did the following: 

uninstalled Nodejs, tried to reinstall the most up to date version, attempted again, got the same error, uninstalled Nodejs again, and then downloaded v20 which has lts and then followed your suggestion of deleting Magic Mirror folder and then reinstalling. 

Once I get back to the pi I can run that command and let you know the output.

**Comment by sdetweil** [comment]
ok, thanks

**Comment by sdetweil** [comment]
still hoping you can send that output.. thanks
